/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 AMDRyzen7-5700.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const AMDRyzen75700=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cpu/AMDRyzen7-5700.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['AMDRyzen7-5700'].geometry} material={materials['AMDRyzen7-5700']} />
    </group>
  )
}

const AMDRyzen7Canvas=()=>{
  return(
    <Canvas
      camera={{fov: 3}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <AMDRyzen75700/>
        </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/cpu/AMDRyzen7-5700.glb')

export default AMDRyzen7Canvas