/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 AMDRyzen5-5600.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const AMDRyzen55600=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cpu/AMDRyzen5-5600.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['AMDRyzen5-5600'].geometry} material={materials['AMDRyzen5-5600']} />
    </group>
  )
}

const AMDRyzen5Canvas=()=>{
  return(
    <Canvas
      camera={{fov: 3}}>
      <Suspense>
        <ambientLight intensity={2} color={"white"}/>
        <OrbitControls/>
        <AMDRyzen55600/>
      </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/cpu/AMDRyzen5-5600.glb')

export default AMDRyzen5Canvas