/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 AMDRyzen9-5950x.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const AMDRyzen95950x=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cpu/AMDRyzen9-5950x.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['AMDRyzen9-5950x'].geometry} material={materials['AMDRyzen9-5950x']} />
    </group>
  )
}

const AMDRyzen9Canvas=()=>{
  return(
    <Canvas
      camera={{fov: 3}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <AMDRyzen95950x/>
        </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/cpu/AMDRyzen9-5950x.glb')

export default AMDRyzen9Canvas