/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 AsusEX-A320M-Gaming.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const AsusEXA320MGaming =(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/motherboards/AsusEX-A320M-Gaming.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['AsusEX-A320M-Gaming_1'].geometry} material={materials.darkgrey} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_2'].geometry} material={materials.gold} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_3'].geometry} material={materials['AsusEX-A320-GamingFrontSide']} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_4'].geometry} material={materials['AsusEX-A320-GamingBackSide']} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_5'].geometry} material={materials.MetallicGrey} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_6'].geometry} material={materials.lightpurple} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_7'].geometry} material={materials.cyan} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_8'].geometry} material={materials.lightred} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_9'].geometry} material={materials.lightdarkgrey} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_10'].geometry} material={materials.DarkBlue} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_11'].geometry} material={materials.red} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_12'].geometry} material={materials['AsusRogStrixB350-IBase']} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_13'].geometry} material={materials.softred} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_14'].geometry} material={materials.lightgreen} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_15'].geometry} material={materials.skyblue} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_16'].geometry} material={materials.WhiteMaterialImage} />
      <mesh geometry={nodes['AsusEX-A320M-Gaming_17'].geometry} material={materials.MotherboardBaseFrontSide} />
    </group>
  )
}

const AsusEXA320MGamingCanvas =()=>{
  return(
    <Canvas
      camera={{fov: 16}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <AsusEXA320MGaming/>
        </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/motherboards/AsusEX-A320M-Gaming.glb')

export default AsusEXA320MGamingCanvas