/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 AsusRogStrixB350-I.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const AsusRogStrixB350I=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/motherboards/AsusRogStrixB350-I.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes['AsusRogStrixB350-I_1'].geometry} material={materials.darkgrey} />
        <mesh geometry={nodes['AsusRogStrixB350-I_2'].geometry} material={materials['AsusRogStrixB350-IBase']} />
        <mesh geometry={nodes['AsusRogStrixB350-I_3'].geometry} material={materials['AsusRogStixB350-IBaseBack']} />
        <mesh geometry={nodes['AsusRogStrixB350-I_4'].geometry} material={materials.MetallicGrey} />
        <mesh geometry={nodes['AsusRogStrixB350-I_5'].geometry} material={materials.gold} />
        <mesh geometry={nodes['AsusRogStrixB350-I_6'].geometry} material={materials.lightdarkgrey} />
        <mesh geometry={nodes['AsusRogStrixB350-I_7'].geometry} material={materials.MotherboardBaseFrontSide} />
        <mesh geometry={nodes['AsusRogStrixB350-I_8'].geometry} material={materials.red} />
        <mesh geometry={nodes['AsusRogStrixB350-I_9'].geometry} material={materials.DarkBlue} />
        <mesh geometry={nodes['AsusRogStrixB350-I_10'].geometry} material={materials.WhiteMaterialImage} />
      </group>
    </group>
  )
}

const AsusRogStrixB350ICanvas=()=>{
  return(
    <Canvas
      camera={{fov: 12}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <AsusRogStrixB350I position-y={-0.1}/>
        </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/motherboards/AsusRogStrixB350-I.glb')

export default AsusRogStrixB350ICanvas