/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CoolerMasterCaseMaker5t.glb 
*/

import React, { useContext, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { AnimationContext } from '../../App'
import { playAnimation, stopAnimation } from '../componentLogic/AnimationLogic'

const CoolerMasterCaseMaker5t = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/pc_parts/pc_cases/CoolerMasterCaseMaker5t.glb')
  const { actions, mixer } = useAnimations(animations, group)

  const {
    lCaseBigMBSlide, setLCaseBigMBSlide,
    lCaseMedMBSlide, setLCaseMedMBSlide,
    lCaseSmlMBSlide, setLCaseSmlMBSlide,
    bigCaseSide1Slide, setBigCaseSide1Slide,
    amdRyzen5BIGMB, setAMDRyzen5BIGMB,
    amdRyzen7BIGMB, setAMDRyzen7BIGMB,
    amdRyzen9BIGMB, setAMDRyzen9BIGMB,
    amdRyzen5MEDMB, setAMDRyzen5MEDMB,
    amdRyzen7MEDMB, setAMDRyzen7MEDMB,
    amdRyzen9MEDMB, setAMDRyzen9MEDMB,
    amdRyzen5SMLMB, setAMDRyzen5SMLMB,
    amdRyzen7SMLMB, setAMDRyzen7SMLMB,
    amdRyzen9SMLMB, setAMDRyzen9SMLMB,
    RTX3070BIGMBtop, setRTX3070BIGMBtop,
    RTX3070BIGMBbot, setRTX3070BIGMBbot,
    RTX3080BIGMBtop, setRTX3080BIGMBtop,
    RTX3080BIGMBbot, setRTX3080BIGMBbot,
    RTX3090BIGMBtop, setRTX3090BIGMBtop,
    RTX3090BIGMBbot, setRTX3090BIGMBbot,
    RTX3070MEDMB, setRTX3070MEDMB,
    RTX3080MEDMB, setRTX3080MEDMB,
    RTX3090MEDMB, setRTX3090MEDMB,
    RTX3070SMLMB, setRTX3070SMLMB,
    RTX3080SMLMB, setRTX3080SMLMB,
    RTX3090SMLMB, setRTX3090SMLMB,
    HPV8GBRAMBIGMBslot1, setHPV8GBRAMBIGMBslot1,
    HPV8GBRAMBIGMBslot2, setHPV8GBRAMBIGMBslot2,
    HPV8GBRAMBIGMBslot3, setHPV8GBRAMBIGMBslot3,
    HPV8GBRAMBIGMBslot4, setHPV8GBRAMBIGMBslot4,
    KFBeast16BGRAMBIGMBslot1, setKFBeast16BGRAMBIGMBslot1,
    KFBeast16BGRAMBIGMBslot2, setKFBeast16BGRAMBIGMBslot2,
    KFBeast16BGRAMBIGMBslot3, setKFBeast16BGRAMBIGMBslot3,
    KFBeast16BGRAMBIGMBslot4, setKFBeast16BGRAMBIGMBslot4,
    HPV8GBRAMMEDMBslot1, setHPV8GBRAMMEDMBslot1,
    HPV8GBRAMMEDMBslot2, setHPV8GBRAMMEDMBslot2,
    HPV8GBRAMMEDMBslot3, setHPV8GBRAMMEDMBslot3,
    HPV8GBRAMMEDMBslot4, setHPV8GBRAMMEDMBslot4,
    KFBeast16BGRAMMEDMBslot1, setKFBeast16BGRAMMEDMBslot1,
    KFBeast16BGRAMMEDMBslot2, setKFBeast16BGRAMMEDMBslot2,
    KFBeast16BGRAMMEDMBslot3, setKFBeast16BGRAMMEDMBslot3,
    KFBeast16BGRAMMEDMBslot4, setKFBeast16BGRAMMEDMBslot4,
    HPV8GBRAMSMLMBslot1, setHPV8GBRAMSMLMBslot1,
    HPV8GBRAMSMLMBslot2, setHPV8GBRAMSMLMBslot2,
    KFBeast16BGRAMSMLMBslot1, setKFBeast16BGRAMSMLMBslot1,
    KFBeast16BGRAMSMLMBslot2, setKFBeast16BGRAMSMLMBslot2,
    beast8GBRam, setbeast8GBRam,
    HP16BGRam, setHP16BGRam,
    CX550PowerunitBIG, setCX550PowerunitBIG,
    HX850PowerunitBIG, setHX850PowerunitBIG,
    HX1200PowerunitBIG, setHX1200PowerunitBIG,
    Samsung870EVOBIGs, setSamsung870EVOBIGs,
    Samsung970SlotsBIGSlot1, setSamsung970SlotsBIGSlot1,
    Samsung970SlotsBIGSlot2, setSamsung970SlotsBIGSlot2,
    Samsung970SlotsMED, setSamsung970SlotsMED,
    SeagateBarraCuda2TBBIGs, setSeagateBarraCuda2TBBIGs,
    CorsairAFSLIMBIGs, setCorsairAFSLIMBIGs,
    CorsairICUELINKQXBIGs, setCorsairICUELINKQXBIGs,
    CorsairAFELITEBIGs, setCorsairAFELITEBIGs
  } = useContext(AnimationContext);

  const hideTop = () => {
    playAnimation(actions.HideHDDHolder2)
  }

  const hideBot = () => {
    playAnimation(actions.HideHDDHolder1)
  }

  const hideBackPanel = () => {
    playAnimation(actions.BackPanelPowerBoxFrameSlide)
  }


  useEffect(() => {
    if (lCaseBigMBSlide == false && lCaseMedMBSlide == false && lCaseSmlMBSlide == false) {
      setbeast8GBRam(false)
      setHP16BGRam(false)
      setCX550PowerunitBIG(false)
      setHX850PowerunitBIG(false)
      setHX1200PowerunitBIG(false)
    }
    if (lCaseBigMBSlide) {
      playAnimation(actions.MSIX370XPowerGamingTitatnumMovingInPlace)
    } else if (lCaseBigMBSlide == false) {
      stopAnimation(actions.MSIX370XPowerGamingTitatnumMovingInPlace)
      setAMDRyzen5BIGMB(false)
      setAMDRyzen7BIGMB(false)
      setAMDRyzen9BIGMB(false)
      setRTX3070BIGMBtop(false)
      setRTX3070BIGMBbot(false)
      setRTX3080BIGMBtop(false)
      setRTX3080BIGMBbot(false)
      setRTX3090BIGMBtop(false)
      setRTX3090BIGMBbot(false)
      setHPV8GBRAMBIGMBslot1(false)
      setHPV8GBRAMBIGMBslot2(false)
      setHPV8GBRAMBIGMBslot3(false)
      setHPV8GBRAMBIGMBslot4(false)
      setKFBeast16BGRAMBIGMBslot1(false)
      setKFBeast16BGRAMBIGMBslot2(false)
      setKFBeast16BGRAMBIGMBslot3(false)
      setKFBeast16BGRAMBIGMBslot4(false)
      setSamsung970SlotsBIGSlot1(false)
      setSamsung970SlotsBIGSlot2(false)
    }
    if (lCaseMedMBSlide) {
      playAnimation(actions.AsusEXA320MSlide)
    } else if (lCaseMedMBSlide == false) {
      stopAnimation(actions.AsusEXA320MSlide)
      setAMDRyzen5MEDMB(false)
      setAMDRyzen7MEDMB(false)
      setAMDRyzen9MEDMB(false)
      setRTX3070MEDMB(false)
      setRTX3080MEDMB(false)
      setRTX3090MEDMB(false)
      setHPV8GBRAMMEDMBslot1(false)
      setHPV8GBRAMMEDMBslot2(false)
      setHPV8GBRAMMEDMBslot3(false)
      setHPV8GBRAMMEDMBslot4(false)
      setKFBeast16BGRAMMEDMBslot1(false)
      setKFBeast16BGRAMMEDMBslot2(false)
      setKFBeast16BGRAMMEDMBslot3(false)
      setKFBeast16BGRAMMEDMBslot4(false)
    }
    if (lCaseSmlMBSlide) {
      playAnimation(actions.AsusRogStrixB350ISlide)
    } else if (lCaseSmlMBSlide == false) {
      stopAnimation(actions.AsusRogStrixB350ISlide)
      setAMDRyzen5SMLMB(false)
      setAMDRyzen7SMLMB(false)
      setAMDRyzen9SMLMB(false)
      setRTX3070SMLMB(false)
      setRTX3080SMLMB(false)
      setRTX3090SMLMB(false)
      setHPV8GBRAMSMLMBslot1(false)
      setHPV8GBRAMSMLMBslot2(false)
      setKFBeast16BGRAMSMLMBslot1(false)
      setKFBeast16BGRAMSMLMBslot2(false)
      setSamsung970SlotsMED(false)
    }
    if (bigCaseSide1Slide) {
      playAnimation(actions.SidePanelSlide)
      playAnimation(actions.SidePanelSlide2)
    } else if (bigCaseSide1Slide == false) {
      stopAnimation(actions.SidePanelSlide)
      stopAnimation(actions.SidePanelSlide2)
    }
    if (amdRyzen5BIGMB) {
      playAnimation(actions.AMDRyzen5BIGMBSlide)
    } else if (amdRyzen5BIGMB == false) {
      stopAnimation(actions.AMDRyzen5BIGMBSlide)
    }
    if (amdRyzen7BIGMB) {
      playAnimation(actions.AMDRyzen7BIGMBSlide)
    } else if (amdRyzen7BIGMB == false) {
      stopAnimation(actions.AMDRyzen7BIGMBSlide)
    }
    if (amdRyzen9BIGMB) {
      playAnimation(actions.AMDRyzen9BIGMBSlide)
    } else if (amdRyzen9BIGMB == false) {
      stopAnimation(actions.AMDRyzen9BIGMBSlide)
    }
    if (amdRyzen5MEDMB) {
      playAnimation(actions.AMDRyzen5MEDMBSlide)
    } else if (amdRyzen5MEDMB == false) {
      stopAnimation(actions.AMDRyzen5MEDMBSlide)
    }
    if (amdRyzen7MEDMB) {
      playAnimation(actions.AMDRyzen7MEDMBSlide)
    } else if (amdRyzen7MEDMB == false) {
      stopAnimation(actions.AMDRyzen7MEDMBSlide)
    }
    if (amdRyzen9MEDMB) {
      playAnimation(actions.AMDRyzen9MEDMBSlide)
    } else if (amdRyzen9MEDMB == false) {
      stopAnimation(actions.AMDRyzen9MEDMBSlide)
    }
    if (amdRyzen5SMLMB) {
      playAnimation(actions.AMDRyzen5SMLMBSlide)
    } else if (amdRyzen5SMLMB == false) {
      stopAnimation(actions.AMDRyzen5SMLMBSlide)
    }
    if (amdRyzen7SMLMB) {
      playAnimation(actions.AMDRyzen7SMLMBSlide)
    } else if (amdRyzen7SMLMB == false) {
      stopAnimation(actions.AMDRyzen7SMLMBSlide)
    }
    if (amdRyzen9SMLMB) {
      playAnimation(actions.AMDRyzen9SMLMBSlide)
    } else if (amdRyzen9SMLMB == false) {
      stopAnimation(actions.AMDRyzen9SMLMBSlide)
    }
    if (RTX3070BIGMBtop) {
      playAnimation(actions.NvidiaGeForceRTX3070BIGMBTopSlot)
    } else if (RTX3070BIGMBtop == false) {
      stopAnimation(actions.NvidiaGeForceRTX3070BIGMBTopSlot)
    }
    if (RTX3070BIGMBbot) {
      playAnimation(actions.NvidiaGeForceRTX3070BIGMBBottomSlot)
    } else if (RTX3070BIGMBbot == false) {
      stopAnimation(actions.NvidiaGeForceRTX3070BIGMBBottomSlot)
    }
    if (RTX3070MEDMB) {
      playAnimation(actions.NvidiaGeForceRTX3070MEDMBSlot)
    } else if (RTX3070MEDMB == false) {
      stopAnimation(actions.NvidiaGeForceRTX3070MEDMBSlot)
    }
    if (RTX3070SMLMB) {
      playAnimation(actions.NvidiaGeForceRTX3070SMLMBSlot)
    } else if (RTX3070SMLMB == false) {
      stopAnimation(actions.NvidiaGeForceRTX3070SMLMBSlot)
    }
    if (RTX3080BIGMBtop) {
      playAnimation(actions.NvidiaGeForceRTX3080BIGMBTopSlot)
    } else if (RTX3080BIGMBtop == false) {
      stopAnimation(actions.NvidiaGeForceRTX3080BIGMBTopSlot)
    }
    if (RTX3080BIGMBbot) {
      playAnimation(actions.NvidiaGeForceRTX3080BIGMBBottomSlot)
    } else if (RTX3080BIGMBbot == false) {
      stopAnimation(actions.NvidiaGeForceRTX3080BIGMBBottomSlot)
    }
    if (RTX3080MEDMB) {
      playAnimation(actions.NvidiaGeForceRTX3080MEDMB)
    } else if (RTX3080MEDMB == false) {
      stopAnimation(actions.NvidiaGeForceRTX3080MEDMB)
    }
    if (RTX3080SMLMB) {
      playAnimation(actions.NvidiaGeForceRTX3080SMLMB)
    } else if (RTX3080SMLMB == false) {
      stopAnimation(actions.NvidiaGeForceRTX3080SMLMB)
    }
    if (RTX3090BIGMBtop) {
      playAnimation(actions.NvidiaGeForceRTX3090BIGMBTopSlot)
      hideTop()
    } else if (RTX3090BIGMBtop == false) {
      stopAnimation(actions.NvidiaGeForceRTX3090BIGMBTopSlot)
    }
    if (RTX3090BIGMBbot) {
      playAnimation(actions.NvidiaGeForceRTX3090BIGMBBottomSlot)
      hideBot()
    } else if (RTX3090BIGMBbot == false) {
      stopAnimation(actions.NvidiaGeForceRTX3090BIGMBBottomSlot)
      stopAnimation(actions.HideHDDHolder1)
    }
    if (RTX3090MEDMB) {
      playAnimation(actions.NvidiaGeForceRTX3090MEDMBSlot)
      hideTop()
    } else if (RTX3090MEDMB == false) {
      stopAnimation(actions.NvidiaGeForceRTX3090MEDMBSlot)
    }
    if (RTX3090SMLMB) {
      playAnimation(actions.NvidiaGeForceRTX3090SMLMBSlot)
      hideTop()
    } else if (RTX3090SMLMB == false) {
      stopAnimation(actions.NvidiaGeForceRTX3090SMLMBSlot)
    }
    if (RTX3090SMLMB == true || RTX3090MEDMB == true || RTX3090BIGMBtop == true) {
      hideTop()
    } else {
      stopAnimation(actions.HideHDDHolder2)
    }

    if (HPV8GBRAMBIGMBslot1) {
      playAnimation(actions.DIMM16GBSlot1BIGMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot1BIGMB)
    }
    if (HPV8GBRAMBIGMBslot2) {
      playAnimation(actions.DIMM16GBSlot2BIGMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot2BIGMB)
    }
    if (HPV8GBRAMBIGMBslot3) {
      playAnimation(actions.DIMM16GBSlot3BIGMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot3BIGMB)
    }
    if (HPV8GBRAMBIGMBslot4) {
      playAnimation(actions.DIMM16GBSlot4BIGMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot4BIGMB)
    }
    if (HPV8GBRAMMEDMBslot1) {
      playAnimation(actions.DIMM16GBSlot1MEDMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot1MEDMB)
    }
    if (HPV8GBRAMMEDMBslot2) {
      playAnimation(actions.DIMM16GBSlot2MEDMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot2MEDMB)
    }
    if (HPV8GBRAMMEDMBslot3) {
      playAnimation(actions.DIMM16GBSlot3MEDMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot3MEDMB)
    }
    if (HPV8GBRAMMEDMBslot4) {
      playAnimation(actions.DIMM16GBSlot4MEDMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot4MEDMB)
    }
    if (HPV8GBRAMSMLMBslot1) {
      playAnimation(actions.DIMM16GBSlot1SMLMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot1SMLMB)
    }
    if (HPV8GBRAMSMLMBslot2) {
      playAnimation(actions.DIMM16GBSlot2SMLMB)
    } else {
      stopAnimation(actions.DIMM16GBSlot2SMLMB)
    }
    if (KFBeast16BGRAMBIGMBslot1) {
      playAnimation(actions.Beast8GBSlot1BIGMB)
    } else {
      stopAnimation(actions.Beast8GBSlot1BIGMB)
    }
    if (KFBeast16BGRAMBIGMBslot2) {
      playAnimation(actions.Beast8GBSlot2BIGMB)
    } else {
      stopAnimation(actions.Beast8GBSlot2BIGMB)
    }
    if (KFBeast16BGRAMBIGMBslot3) {
      playAnimation(actions.Beast8GBSlot3BIGMB)
    } else {
      stopAnimation(actions.Beast8GBSlot3BIGMB)
    }
    if (KFBeast16BGRAMBIGMBslot4) {
      playAnimation(actions.Beast8GBSlot4BIGMB)
    } else {
      stopAnimation(actions.Beast8GBSlot4BIGMB)
    }
    if (KFBeast16BGRAMMEDMBslot1) {
      playAnimation(actions.Beast8GBSlot1MEDMB)
    } else {
      stopAnimation(actions.Beast8GBSlot1MEDMB)
    }
    if (KFBeast16BGRAMMEDMBslot2) {
      playAnimation(actions.Beast8GBSlot2MEDMB)
    } else {
      stopAnimation(actions.Beast8GBSlot2MEDMB)
    }
    if (KFBeast16BGRAMMEDMBslot3) {
      playAnimation(actions.Beast8GBSlot3MEDMB)
    } else {
      stopAnimation(actions.Beast8GBSlot3MEDMB)
    }
    if (KFBeast16BGRAMMEDMBslot4) {
      playAnimation(actions.Beast8GBSlot4MEDMB)
    } else {
      stopAnimation(actions.Beast8GBSlot4MEDMB)
    }
    if (KFBeast16BGRAMSMLMBslot1) {
      playAnimation(actions.Beast8GBSlot1SMLMB)
    } else {
      stopAnimation(actions.Beast8GBSlot1SMLMB)
    }
    if (KFBeast16BGRAMSMLMBslot2) {
      playAnimation(actions.Beast8GBSlot2SMLMB)
    } else {
      stopAnimation(actions.Beast8GBSlot2SMLMB)
    }
    if (CX550PowerunitBIG) {
      playAnimation(actions.CX550PowerunitMovieInPlace)
    } else {
      stopAnimation(actions.CX550PowerunitMovieInPlace)
    }
    if (HX850PowerunitBIG) {
      playAnimation(actions.HX850PowerUnitMoveInPlace)
    } else {
      stopAnimation(actions.HX850PowerUnitMoveInPlace)
    }
    if (HX1200PowerunitBIG) {
      playAnimation(actions.HX1200PowerUnitMoveInPlace)
    } else {
      stopAnimation(actions.HX1200PowerUnitMoveInPlace)
    }
    if (CX550PowerunitBIG == true || HX850PowerunitBIG == true || HX1200PowerunitBIG == true) {
      hideBackPanel()
    } else {
      stopAnimation(actions.BackPanelPowerBoxFrameSlide)
    }

    if (Samsung870EVOBIGs[0].slot == true) {
      playAnimation(actions.Samsung870EVOSlot3Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot3Front)
    }
    if (Samsung870EVOBIGs[1].slot == true) {
      playAnimation(actions.Samsung870EVOSlot4Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot4Front)
    }
    if (Samsung870EVOBIGs[2].slot == true) {
      playAnimation(actions.Samsung870EVOSlot5Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot5Front)
    }
    if (Samsung870EVOBIGs[3].slot == true) {
      playAnimation(actions.Samsung870EVOSlot6Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot6Front)
    }
    if (Samsung870EVOBIGs[4].slot == true) {
      playAnimation(actions.Samsung870EVOSlot7Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot7Front)
    }
    if (Samsung870EVOBIGs[5].slot == true) {
      playAnimation(actions.Samsung870EVOSlot8Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot8Front)
    }
    if (Samsung870EVOBIGs[6].slot == true) {
      playAnimation(actions.Samsung870EVOSlot9Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot9Front)
    }
    if (Samsung870EVOBIGs[7].slot == true) {
      playAnimation(actions.Samsung870EVOSlot1Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot1Front)
    }
    if (Samsung870EVOBIGs[8].slot == true) {
      playAnimation(actions.Samsung870EVOSlot2Front)
    } else {
      stopAnimation(actions.Samsung870EVOSlot2Front)
    }
    if (Samsung870EVOBIGs[9].slot == true) {
      playAnimation(actions.Samsung870EVOSlot1Back)
    } else {
      stopAnimation(actions.Samsung870EVOSlot1Back)
    }
    if (Samsung870EVOBIGs[10].slot == true) {
      playAnimation(actions.Samsung870EVOSlot2Back)
    } else {
      stopAnimation(actions.Samsung870EVOSlot2Back)
    }

    if (Samsung970SlotsBIGSlot1) {
      playAnimation(actions.Samsung970EVOPlusBIGMBM2Slot1)

    } else {
      stopAnimation(actions.Samsung970EVOPlusBIGMBM2Slot1)
    }
    if (Samsung970SlotsBIGSlot2) {
      playAnimation(actions.Samsung970EVOPlusBIGMBM2Slot2)
      playAnimation(actions.MSIX370XPowerGamingTitatnumSHIELD)
    } else {
      stopAnimation(actions.Samsung970EVOPlusBIGMBM2Slot2)
      stopAnimation(actions.MSIX370XPowerGamingTitatnumSHIELD)
    }
    if (Samsung970SlotsMED) {
      playAnimation(actions.Samsung970EVOPlusMEDMBM2Slot1)
    } else {
      stopAnimation(actions.Samsung970EVOPlusMEDMBM2Slot1)
    }
    
    if (SeagateBarraCuda2TBBIGs[0].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot1)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot1)
    }
    if (SeagateBarraCuda2TBBIGs[1].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot2)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot2)
    }
    if (SeagateBarraCuda2TBBIGs[2].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot3)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot3)
    }
    if (SeagateBarraCuda2TBBIGs[3].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot4)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot4)
    }
    if (SeagateBarraCuda2TBBIGs[4].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot5)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot5)
    }
    if (SeagateBarraCuda2TBBIGs[5].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot6)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot6)
    }
    if (SeagateBarraCuda2TBBIGs[6].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot7)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot7)
    }

    if (CorsairAFSLIMBIGs[1].slot) {
      playAnimation(actions.TopBlack120mmFanSlot1)
    } else {
      stopAnimation(actions.TopBlack120mmFanSlot1)
    }
    if (CorsairAFSLIMBIGs[4].slot) {
      playAnimation(actions.TopBlack120mmFanSlot2)
    } else {
      stopAnimation(actions.TopBlack120mmFanSlot2)
    }
    if (CorsairAFSLIMBIGs[2].slot) {
      playAnimation(actions.TopBlack140mmFanSlot1)
    } else {
      stopAnimation(actions.TopBlack140mmFanSlot1)
    }
    if (CorsairAFSLIMBIGs[5].slot) {
      playAnimation(actions.TopBlack140mmFanSlot2)
    } else {
      stopAnimation(actions.TopBlack140mmFanSlot2)
    }

    if (CorsairICUELINKQXBIGs[1].slot) {
      playAnimation(actions.TopWhite120mmFanSlot1)
    } else {
      stopAnimation(actions.TopWhite120mmFanSlot1)
    }
    if (CorsairICUELINKQXBIGs[4].slot) {
      playAnimation(actions.TopWhite120mmFanSlot2)
    } else {
      stopAnimation(actions.TopWhite120mmFanSlot2)
    }
    if (CorsairICUELINKQXBIGs[2].slot) {
      playAnimation(actions.TopWhiteFan140mmSlot1)
    } else {
      stopAnimation(actions.TopWhiteFan140mmSlot1)
    }
    if (CorsairICUELINKQXBIGs[5].slot) {
      playAnimation(actions.TopWhite140mmFanSlot2)
    } else {
      stopAnimation(actions.TopWhite140mmFanSlot2)
    }

    if (CorsairAFELITEBIGs[1].slot) {
      playAnimation(actions.TopSBlack120mmFanSlot1)
    } else {
      stopAnimation(actions.TopSBlack120mmFanSlot1)
    }
    if (CorsairAFELITEBIGs[4].slot) {
      playAnimation(actions.TopSBlack120mmFanSlot2)
    } else {
      stopAnimation(actions.TopSBlack120mmFanSlot2)
    }
    if (CorsairAFELITEBIGs[2].slot) {
      playAnimation(actions.TopSBlackFan140mmSlot1)
    } else {
      stopAnimation(actions.TopSBlackFan140mmSlot1)
    }
    if (CorsairAFELITEBIGs[5].slot) {
      playAnimation(actions.TopSBlack140mmFanSlot2)
    } else {
      stopAnimation(actions.TopSBlack140mmFanSlot2)
    }



  }, [mixer,
    lCaseBigMBSlide, lCaseMedMBSlide, lCaseSmlMBSlide, bigCaseSide1Slide,
    amdRyzen5BIGMB, amdRyzen7BIGMB, amdRyzen9BIGMB,
    amdRyzen5MEDMB, amdRyzen7MEDMB, amdRyzen9MEDMB,
    amdRyzen5SMLMB, amdRyzen7SMLMB, amdRyzen9SMLMB,
    RTX3070BIGMBtop, RTX3070BIGMBbot, RTX3070MEDMB, RTX3070SMLMB,
    RTX3080BIGMBtop, RTX3080BIGMBbot, RTX3080MEDMB, RTX3080SMLMB,
    RTX3090BIGMBtop, RTX3090BIGMBbot, RTX3090MEDMB, RTX3090SMLMB,
    HPV8GBRAMBIGMBslot1, HPV8GBRAMBIGMBslot2, HPV8GBRAMBIGMBslot3, HPV8GBRAMBIGMBslot4,
    HPV8GBRAMMEDMBslot1, HPV8GBRAMMEDMBslot2, HPV8GBRAMMEDMBslot3, HPV8GBRAMMEDMBslot4,
    HPV8GBRAMSMLMBslot1, HPV8GBRAMSMLMBslot2,
    KFBeast16BGRAMBIGMBslot1, KFBeast16BGRAMBIGMBslot2, KFBeast16BGRAMBIGMBslot3, KFBeast16BGRAMBIGMBslot4,
    KFBeast16BGRAMMEDMBslot1, KFBeast16BGRAMMEDMBslot2, KFBeast16BGRAMMEDMBslot3, KFBeast16BGRAMMEDMBslot4,
    KFBeast16BGRAMSMLMBslot1, KFBeast16BGRAMSMLMBslot2,
    CX550PowerunitBIG, HX850PowerunitBIG, HX1200PowerunitBIG,
    Samsung870EVOBIGs, Samsung970SlotsBIGSlot1, Samsung970SlotsBIGSlot2, Samsung970SlotsMED,
    SeagateBarraCuda2TBBIGs, CorsairAFSLIMBIGs, CorsairICUELINKQXBIGs, CorsairAFELITEBIGs
  ])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AsusEX-A320M-Gaming" position={[-0.579, 1.842, 5.017]} scale={0}>
          <mesh name="AsusEX-A320M-Gaming_1" geometry={nodes['AsusEX-A320M-Gaming_1'].geometry} material={materials['darkgrey.001']} />
          <mesh name="AsusEX-A320M-Gaming_2" geometry={nodes['AsusEX-A320M-Gaming_2'].geometry} material={materials['gold.001']} />
          <mesh name="AsusEX-A320M-Gaming_3" geometry={nodes['AsusEX-A320M-Gaming_3'].geometry} material={materials['AsusEX-A320-GamingFrontSide']} />
          <mesh name="AsusEX-A320M-Gaming_4" geometry={nodes['AsusEX-A320M-Gaming_4'].geometry} material={materials['AsusEX-A320-GamingBackSide']} />
          <mesh name="AsusEX-A320M-Gaming_5" geometry={nodes['AsusEX-A320M-Gaming_5'].geometry} material={materials['MetallicGrey.001']} />
          <mesh name="AsusEX-A320M-Gaming_6" geometry={nodes['AsusEX-A320M-Gaming_6'].geometry} material={materials.lightpurple} />
          <mesh name="AsusEX-A320M-Gaming_7" geometry={nodes['AsusEX-A320M-Gaming_7'].geometry} material={materials.cyan} />
          <mesh name="AsusEX-A320M-Gaming_8" geometry={nodes['AsusEX-A320M-Gaming_8'].geometry} material={materials.lightred} />
          <mesh name="AsusEX-A320M-Gaming_9" geometry={nodes['AsusEX-A320M-Gaming_9'].geometry} material={materials['lightdarkgrey.001']} />
          <mesh name="AsusEX-A320M-Gaming_10" geometry={nodes['AsusEX-A320M-Gaming_10'].geometry} material={materials['DarkBlue.001']} />
          <mesh name="AsusEX-A320M-Gaming_11" geometry={nodes['AsusEX-A320M-Gaming_11'].geometry} material={materials['red.001']} />
          <mesh name="AsusEX-A320M-Gaming_12" geometry={nodes['AsusEX-A320M-Gaming_12'].geometry} material={materials['AsusRogStrixB350-IBase']} />
          <mesh name="AsusEX-A320M-Gaming_13" geometry={nodes['AsusEX-A320M-Gaming_13'].geometry} material={materials.softred} />
          <mesh name="AsusEX-A320M-Gaming_14" geometry={nodes['AsusEX-A320M-Gaming_14'].geometry} material={materials.lightgreen} />
          <mesh name="AsusEX-A320M-Gaming_15" geometry={nodes['AsusEX-A320M-Gaming_15'].geometry} material={materials.skyblue} />
          <mesh name="AsusEX-A320M-Gaming_16" geometry={nodes['AsusEX-A320M-Gaming_16'].geometry} material={materials['WhiteMaterialImage.001']} />
          <mesh name="AsusEX-A320M-Gaming_17" geometry={nodes['AsusEX-A320M-Gaming_17'].geometry} material={materials['MotherboardBaseFrontSide.001']} />
        </group>
        <group name="AsusRogStrixB350-I" position={[-0.655, 1.896, 5.027]} scale={0}>
          <mesh name="AsusRogStrixB350-I_1" geometry={nodes['AsusRogStrixB350-I_1'].geometry} material={materials['darkgrey.001']} />
          <mesh name="AsusRogStrixB350-I_2" geometry={nodes['AsusRogStrixB350-I_2'].geometry} material={materials['AsusRogStrixB350-IBase']} />
          <mesh name="AsusRogStrixB350-I_3" geometry={nodes['AsusRogStrixB350-I_3'].geometry} material={materials['AsusRogStixB350-IBaseBack']} />
          <mesh name="AsusRogStrixB350-I_4" geometry={nodes['AsusRogStrixB350-I_4'].geometry} material={materials['MetallicGrey.001']} />
          <mesh name="AsusRogStrixB350-I_5" geometry={nodes['AsusRogStrixB350-I_5'].geometry} material={materials['gold.001']} />
          <mesh name="AsusRogStrixB350-I_6" geometry={nodes['AsusRogStrixB350-I_6'].geometry} material={materials['lightdarkgrey.001']} />
          <mesh name="AsusRogStrixB350-I_7" geometry={nodes['AsusRogStrixB350-I_7'].geometry} material={materials['MotherboardBaseFrontSide.001']} />
          <mesh name="AsusRogStrixB350-I_8" geometry={nodes['AsusRogStrixB350-I_8'].geometry} material={materials['red.001']} />
          <mesh name="AsusRogStrixB350-I_9" geometry={nodes['AsusRogStrixB350-I_9'].geometry} material={materials['DarkBlue.001']} />
          <mesh name="AsusRogStrixB350-I_10" geometry={nodes['AsusRogStrixB350-I_10'].geometry} material={materials['WhiteMaterialImage.001']} />
        </group>
        <group name="Samsung870EVO" position={[0.604, 0.305, 1.362]} scale={0}>
          <mesh name="Samsung870EVO_1" geometry={nodes.Samsung870EVO_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO_2" geometry={nodes.Samsung870EVO_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO001" position={[0.604, 0.891, 1.362]} scale={0}>
          <mesh name="Samsung870EVO001_1" geometry={nodes.Samsung870EVO001_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO001_2" geometry={nodes.Samsung870EVO001_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO002" position={[0.604, 0.461, 1.362]} scale={0}>
          <mesh name="Samsung870EVO002_1" geometry={nodes.Samsung870EVO002_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO002_2" geometry={nodes.Samsung870EVO002_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO003" position={[0.604, 1.045, 1.362]} scale={0}>
          <mesh name="Samsung870EVO003_1" geometry={nodes.Samsung870EVO003_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO003_2" geometry={nodes.Samsung870EVO003_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO004" position={[0.604, 1.408, 1.362]} scale={0}>
          <mesh name="Samsung870EVO004_1" geometry={nodes.Samsung870EVO004_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO004_2" geometry={nodes.Samsung870EVO004_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO005" position={[0.604, 1.564, 1.362]} scale={0}>
          <mesh name="Samsung870EVO005_1" geometry={nodes.Samsung870EVO005_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO005_2" geometry={nodes.Samsung870EVO005_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO006" position={[0.604, 1.729, 1.362]} scale={0}>
          <mesh name="Samsung870EVO006_1" geometry={nodes.Samsung870EVO006_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO006_2" geometry={nodes.Samsung870EVO006_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO007" position={[-0.526, 0.882, 1.61]} scale={0}>
          <mesh name="Samsung870EVO007_1" geometry={nodes.Samsung870EVO007_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO007_2" geometry={nodes.Samsung870EVO007_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO008" position={[-0.978, 0.882, 1.61]} scale={0}>
          <mesh name="Samsung870EVO008_1" geometry={nodes.Samsung870EVO008_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO008_2" geometry={nodes.Samsung870EVO008_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO009" position={[-0.508, 1.189, -2.16]} scale={0}>
          <mesh name="Samsung870EVO009_1" geometry={nodes.Samsung870EVO009_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO009_2" geometry={nodes.Samsung870EVO009_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO010" position={[-0.87, 1.189, -2.16]} scale={0}>
          <mesh name="Samsung870EVO010_1" geometry={nodes.Samsung870EVO010_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO010_2" geometry={nodes.Samsung870EVO010_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung970EVOPlus" position={[-1.103, 1.093, -0.348]} scale={0}>
          <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.Samsung970EVOPlusfront} />
          <mesh name="Plane008_1" geometry={nodes.Plane008_1.geometry} material={materials.Samsung970EVOPlusback} />
          <mesh name="Plane008_2" geometry={nodes.Plane008_2.geometry} material={materials['darkgrey.001']} />
        </group>
        <group name="Samsung970EVOPlus001" position={[-1.103, 1.417, -0.348]} scale={0}>
          <mesh name="Plane028" geometry={nodes.Plane028.geometry} material={materials.Samsung970EVOPlusfront} />
          <mesh name="Plane028_1" geometry={nodes.Plane028_1.geometry} material={materials.Samsung970EVOPlusback} />
          <mesh name="Plane028_2" geometry={nodes.Plane028_2.geometry} material={materials['darkgrey.001']} />
        </group>
        <group name="Samsung970EVOPlus002" position={[-1.164, 1.36, -0.34]} scale={0}>
          <mesh name="Plane029" geometry={nodes.Plane029.geometry} material={materials.Samsung970EVOPlusfront} />
          <mesh name="Plane029_1" geometry={nodes.Plane029_1.geometry} material={materials.Samsung970EVOPlusback} />
          <mesh name="Plane029_2" geometry={nodes.Plane029_2.geometry} material={materials['darkgrey.001']} />
        </group>
        <group name="SeagateBarraCuda2TB" position={[0.607, 0.312, 2.183]} scale={0}>
          <mesh name="Cube598" geometry={nodes.Cube598.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube598_1" geometry={nodes.Cube598_1.geometry} material={materials['darkgrey.001']} />
          <mesh name="Cube598_2" geometry={nodes.Cube598_2.geometry} material={materials['MetallicGrey.001']} />
          <mesh name="Cube598_3" geometry={nodes.Cube598_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube598_4" geometry={nodes.Cube598_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="SeagateBarraCuda2TB001" position={[0.607, 1.736, 2.183]} scale={0}>
          <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['darkgrey.001']} />
          <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['MetallicGrey.001']} />
          <mesh name="Cube002_3" geometry={nodes.Cube002_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube002_4" geometry={nodes.Cube002_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="SeagateBarraCuda2TB002" position={[0.607, 1.051, 2.183]} scale={0}>
          <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials['darkgrey.001']} />
          <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials['MetallicGrey.001']} />
          <mesh name="Cube003_3" geometry={nodes.Cube003_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube003_4" geometry={nodes.Cube003_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="SeagateBarraCuda2TB003" position={[0.607, 0.896, 2.183]} scale={0}>
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials['darkgrey.001']} />
          <mesh name="Cube005_2" geometry={nodes.Cube005_2.geometry} material={materials['MetallicGrey.001']} />
          <mesh name="Cube005_3" geometry={nodes.Cube005_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube005_4" geometry={nodes.Cube005_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="SeagateBarraCuda2TB004" position={[0.607, 0.466, 2.183]} scale={0}>
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials['darkgrey.001']} />
          <mesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials['MetallicGrey.001']} />
          <mesh name="Cube006_3" geometry={nodes.Cube006_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube006_4" geometry={nodes.Cube006_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="SeagateBarraCuda2TB005" position={[0.607, 1.414, 2.183]} scale={0}>
          <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials['darkgrey.001']} />
          <mesh name="Cube008_2" geometry={nodes.Cube008_2.geometry} material={materials['MetallicGrey.001']} />
          <mesh name="Cube008_3" geometry={nodes.Cube008_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube008_4" geometry={nodes.Cube008_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="SeagateBarraCuda2TB006" position={[0.607, 1.57, 2.183]} scale={0}>
          <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube009_2" geometry={nodes.Cube009_2.geometry} material={materials['darkgrey.001']} />
          <mesh name="Cube009_3" geometry={nodes.Cube009_3.geometry} material={materials['MetallicGrey.001']} />
          <mesh name="Cube009_4" geometry={nodes.Cube009_4.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube009_5" geometry={nodes.Cube009_5.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <mesh name="AMDRyzen9-5950x" geometry={nodes['AMDRyzen9-5950x'].geometry} material={materials['AMDRyzen9-5950x']} position={[-0.816, 2.026, -0.416]} scale={0} />
        <mesh name="AMDRyzen7-5700" geometry={nodes['AMDRyzen7-5700'].geometry} material={materials['AMDRyzen7-5700']} position={[-0.816, 2.026, -0.416]} scale={0} />
        <mesh name="AMDRyzen5-5600" geometry={nodes['AMDRyzen5-5600'].geometry} material={materials['AMDRyzen5-5600']} position={[-0.816, 2.026, -0.416]} scale={0} />
        <mesh name="AMDRyzen5-5600001" geometry={nodes['AMDRyzen5-5600001'].geometry} material={materials['AMDRyzen5-5600']} position={[-1.037, 1.993, -0.271]} scale={0} />
        <mesh name="AMDRyzen5-5600002" geometry={nodes['AMDRyzen5-5600002'].geometry} material={materials['AMDRyzen5-5600']} position={[-1.037, 2.026, -0.416]} scale={0} />
        <mesh name="AMDRyzen7-5700001" geometry={nodes['AMDRyzen7-5700001'].geometry} material={materials['AMDRyzen7-5700']} position={[-1.037, 1.993, -0.271]} scale={0} />
        <mesh name="AMDRyzen7-5700002" geometry={nodes['AMDRyzen7-5700002'].geometry} material={materials['AMDRyzen7-5700']} position={[-1.037, 2.026, -0.416]} scale={0} />
        <mesh name="AMDRyzen9-5950x001" geometry={nodes['AMDRyzen9-5950x001'].geometry} material={materials['AMDRyzen9-5950x']} position={[-1.037, 1.993, -0.271]} scale={0} />
        <mesh name="AMDRyzen9-5950x002" geometry={nodes['AMDRyzen9-5950x002'].geometry} material={materials['AMDRyzen9-5950x']} position={[-1.037, 2.026, -0.416]} scale={0} />
        <group name="CorsairFanBlackv1_140mm" position={[-0.746, 1.699, 1.144]} scale={0}>
          <mesh name="Vert008" geometry={nodes.Vert008.geometry} material={materials.darkgrey} />
          <mesh name="Vert008_1" geometry={nodes.Vert008_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="CorsairFanWhite120mm" position={[-0.746, 1.699, 1.144]} scale={0}>
          <mesh name="Vert009" geometry={nodes.Vert009.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert009_1" geometry={nodes.Vert009_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanBlackv1_120mm" position={[-0.746, 1.699, 1.144]} scale={0}>
          <mesh name="Vert012" geometry={nodes.Vert012.geometry} material={materials.darkgrey} />
          <mesh name="Vert012_1" geometry={nodes.Vert012_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="CorsairFanWhite140mm" position={[-0.259, 1.699, 1.144]} scale={0}>
          <mesh name="Vert014" geometry={nodes.Vert014.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert014_1" geometry={nodes.Vert014_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanBlack120mm" position={[-0.746, 1.699, 1.144]} scale={0}>
          <mesh name="Vert016" geometry={nodes.Vert016.geometry} material={materials.darkgrey} />
          <mesh name="Vert016_1" geometry={nodes.Vert016_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlack140mm" position={[-0.746, 1.699, 1.144]} scale={0}>
          <mesh name="Vert017" geometry={nodes.Vert017.geometry} material={materials.darkgrey} />
          <mesh name="Vert017_1" geometry={nodes.Vert017_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlackv1_140mm004" position={[0.978, 0.604, 0.018]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Vert007" geometry={nodes.Vert007.geometry} material={materials.darkgrey} />
          <mesh name="Vert007_1" geometry={nodes.Vert007_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="CorsairFanBlackv1_140mm002" position={[0.978, 1.321, 0.018]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Vert010" geometry={nodes.Vert010.geometry} material={materials.darkgrey} />
          <mesh name="Vert010_1" geometry={nodes.Vert010_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="CorsairFanBlackv1_140mm003" position={[-1.282, 1.984, 0.199]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Vert018" geometry={nodes.Vert018.geometry} material={materials.darkgrey} />
          <mesh name="Vert018_1" geometry={nodes.Vert018_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="CorsairFanWhite120mm001" position={[-0.259, 1.699, 1.144]} scale={0}>
          <mesh name="Vert001" geometry={nodes.Vert001.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert001_1" geometry={nodes.Vert001_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanBlackv1_140mm001" position={[-0.259, 1.699, 1.144]} scale={0}>
          <mesh name="Vert004" geometry={nodes.Vert004.geometry} material={materials.darkgrey} />
          <mesh name="Vert004_1" geometry={nodes.Vert004_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="CorsairFanBlackv1_120mm001" position={[-0.259, 1.699, 1.144]} scale={0}>
          <mesh name="Vert005" geometry={nodes.Vert005.geometry} material={materials.darkgrey} />
          <mesh name="Vert005_1" geometry={nodes.Vert005_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="CorsairFanBlack140mm001" position={[-0.259, 1.699, 1.144]} scale={0}>
          <mesh name="Vert006" geometry={nodes.Vert006.geometry} material={materials.darkgrey} />
          <mesh name="Vert006_1" geometry={nodes.Vert006_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlack120mm001" position={[-0.259, 1.699, 1.144]} scale={0}>
          <mesh name="Vert011" geometry={nodes.Vert011.geometry} material={materials.darkgrey} />
          <mesh name="Vert011_1" geometry={nodes.Vert011_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanWhite140mm001" position={[-0.746, 1.699, 1.144]} scale={0}>
          <mesh name="Vert002" geometry={nodes.Vert002.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert002_1" geometry={nodes.Vert002_1.geometry} material={materials.FanWhite} />
        </group>
        <mesh name="Box_side_panel" geometry={nodes.Box_side_panel.geometry} material={materials.darkgrey} position={[-0.1, 1.374, -0.61]} rotation={[0, -Math.PI / 2, 0]} scale={[0.978, 1, 1]} />
        <mesh name="Box_front_panel" geometry={nodes.Box_front_panel.geometry} material={materials.PCfront} position={[1.248, 1.139, 0.005]} rotation={[0, -1.57, 0]} />
        <mesh name="Box_power_holder" geometry={nodes.Box_power_holder.geometry} material={materials.darkgrey} position={[-0.571, 0.262, 0.005]} rotation={[0, -Math.PI / 2, 0]} />
        <group name="Box_top_panel" position={[0.064, 2.82, 0.003]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.PCTopish} />
          <mesh name="Cube027_1" geometry={nodes.Cube027_1.geometry} material={materials.darkgrey} />
          <mesh name="Cube027_2" geometry={nodes.Cube027_2.geometry} material={materials.red} />
        </group>
        <mesh name="Plane019" geometry={nodes.Plane019.geometry} material={materials.darkgrey} position={[-0.646, 2.705, 0.011]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Box_side_panel001" geometry={nodes.Box_side_panel001.geometry} material={materials.darkgrey} position={[-0.1, 1.374, 0.624]} rotation={[0, -Math.PI / 2, 0]} scale={[0.978, 1, 1]} />
        <group name="Box_skeleton001" position={[1.15, 2.634, 0.006]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.darkgrey} />
          <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials.darkgrey} />
          <mesh name="Cube022_2" geometry={nodes.Cube022_2.geometry} material={materials.Redish} />
          <mesh name="Cube022_3" geometry={nodes.Cube022_3.geometry} material={materials.RedishBottom} />
          <mesh name="Cube022_4" geometry={nodes.Cube022_4.geometry} material={materials.BlackMetalic} />
          <mesh name="Cube022_5" geometry={nodes.Cube022_5.geometry} material={materials['Material.001']} />
          <mesh name="Cube022_6" geometry={nodes.Cube022_6.geometry} material={materials.red} />
        </group>
        <mesh name="Back_panel" geometry={nodes.Back_panel.geometry} material={materials.darkgrey} position={[-1.346, 1.946, 0.195]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Back_panel_USB_ports" geometry={nodes.Back_panel_USB_ports.geometry} material={materials.darkgrey} position={[-1.281, 1.209, -0.165]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Back_panel_power_box_frame" geometry={nodes.Back_panel_power_box_frame.geometry} material={materials.darkgrey} position={[-1.338, 0.451, 0.002]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.Redupscale} position={[0.187, 1.573, -0.479]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.BlackSurfice} position={[-0.753, 0.744, 0.084]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials.BlackSurfice} position={[0.178, 1.081, -0.521]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials.BlackSurfice} position={[0.178, 1.572, -0.521]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane015" geometry={nodes.Plane015.geometry} material={materials.BlackSurfice} position={[0.178, 2.058, -0.521]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials.BlackSurfice} position={[-0.117, 0.693, 0.025]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane017" geometry={nodes.Plane017.geometry} material={materials.BlackSurfice} position={[0.167, 0.693, 0.025]} rotation={[0, -Math.PI / 2, 0]} />
        <group name="Cube" position={[0.959, 1.352, 0.213]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.darkgrey} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.darkgrey} />
        </group>
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.darkgrey} position={[0.601, 2.18, -0.12]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.darkgrey} position={[0.677, 0.446, 0.018]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.darkgrey} position={[0.607, 1.729, 0.204]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.darkgrey} position={[0.607, 0.46, 0.198]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.darkgrey} position={[0.607, 0.305, 0.204]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials.darkgrey} position={[0.607, 1.045, 0.198]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="HoneyComb008" geometry={nodes.HoneyComb008.geometry} material={materials.darkgrey} position={[-0.808, 0.143, 0.02]} rotation={[0, -Math.PI / 2, 0]} scale={0.053} />
        <mesh name="Bottom_filter" geometry={nodes.Bottom_filter.geometry} material={materials.darkgrey} position={[-0.771, 0.137, 0.02]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Front_big_filter" geometry={nodes.Front_big_filter.geometry} material={materials.darkgrey} position={[1.232, 1.34, 0.015]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Front_small_filter" geometry={nodes.Front_small_filter.geometry} material={materials.darkgrey} position={[1.235, 1.293, 0.016]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.BlackSurfice} position={[-0.753, 0.744, 0.084]} rotation={[0, -Math.PI / 2, 0]} />
        <group name="HX850_Power_unit" position={[-4.86, 0.59, 0.021]} scale={0}>
          <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials.PowerBox1200top} />
          <mesh name="Plane020_1" geometry={nodes.Plane020_1.geometry} material={materials.PowerBoxHX1200back} />
          <mesh name="Plane020_2" geometry={nodes.Plane020_2.geometry} material={materials.PowerBoxHX1200front} />
          <mesh name="Plane020_3" geometry={nodes.Plane020_3.geometry} material={materials.BlackMetalic} />
          <mesh name="Plane020_4" geometry={nodes.Plane020_4.geometry} material={materials.PowerBoxHX850side} />
          <mesh name="Plane020_5" geometry={nodes.Plane020_5.geometry} material={materials.PowerBoxHX850back} />
          <mesh name="Plane020_6" geometry={nodes.Plane020_6.geometry} material={materials.darkgrey} />
        </group>
        <group name="HX1200_Power_unit" position={[-3.999, 0.594, 0.016]} scale={0}>
          <mesh name="Plane065" geometry={nodes.Plane065.geometry} material={materials.PowerBox1200top} />
          <mesh name="Plane065_1" geometry={nodes.Plane065_1.geometry} material={materials.PowerBoxHX1200back} />
          <mesh name="Plane065_2" geometry={nodes.Plane065_2.geometry} material={materials.PowerBoxHX1200front} />
          <mesh name="Plane065_3" geometry={nodes.Plane065_3.geometry} material={materials.PowerBoxHX1200side} />
          <mesh name="Plane065_4" geometry={nodes.Plane065_4.geometry} material={materials.BlackMetalic} />
          <mesh name="Plane065_5" geometry={nodes.Plane065_5.geometry} material={materials.darkgrey} />
        </group>
        <group name="CX550_Power_unit" position={[-3.533, 0.652, -0.046]} scale={0}>
          <mesh name="Torus007" geometry={nodes.Torus007.geometry} material={materials.darkgrey} />
          <mesh name="Torus007_1" geometry={nodes.Torus007_1.geometry} material={materials.CX550Top} />
          <mesh name="Torus007_2" geometry={nodes.Torus007_2.geometry} material={materials.CX550Front} />
          <mesh name="Torus007_3" geometry={nodes.Torus007_3.geometry} material={materials.CX550Side} />
          <mesh name="Torus007_4" geometry={nodes.Torus007_4.geometry} material={materials.CX550Back} />
          <mesh name="Torus007_5" geometry={nodes.Torus007_5.geometry} material={materials.PowerBox1200top} />
          <mesh name="Torus007_6" geometry={nodes.Torus007_6.geometry} material={materials.PowerBoxHX1200back} />
          <mesh name="Torus007_7" geometry={nodes.Torus007_7.geometry} material={materials.PowerBoxHX1200front} />
          <mesh name="Torus007_8" geometry={nodes.Torus007_8.geometry} material={materials['PowerBoxHX1200front.001']} />
        </group>
        <group name="MSIX370XPowerGamingTitatnum" position={[-0.563, 1.629, 4.311]} scale={0}>
          <mesh name="MSIX370XPowerGamingTitatnum_1" geometry={nodes.MSIX370XPowerGamingTitatnum_1.geometry} material={materials.darkgrey} />
          <mesh name="MSIX370XPowerGamingTitatnum_2" geometry={nodes.MSIX370XPowerGamingTitatnum_2.geometry} material={materials.MotherboardBaseFrontSide} />
          <mesh name="MSIX370XPowerGamingTitatnum_3" geometry={nodes.MSIX370XPowerGamingTitatnum_3.geometry} material={materials.MotherboardBaseBackSide} />
          <mesh name="MSIX370XPowerGamingTitatnum_4" geometry={nodes.MSIX370XPowerGamingTitatnum_4.geometry} material={materials.MetallicGrey} />
          <mesh name="MSIX370XPowerGamingTitatnum_5" geometry={nodes.MSIX370XPowerGamingTitatnum_5.geometry} material={materials.red} />
          <mesh name="MSIX370XPowerGamingTitatnum_6" geometry={nodes.MSIX370XPowerGamingTitatnum_6.geometry} material={materials.gold} />
          <mesh name="MSIX370XPowerGamingTitatnum_7" geometry={nodes.MSIX370XPowerGamingTitatnum_7.geometry} material={materials.lightdarkgrey} />
        </group>
        <group name="MSIX370XPowerGamingTitatnumSHIELD" position={[-0.468, 1.412, -0.441]} scale={0}>
          <mesh name="MSIX370XPowerGamingTitatnum001" geometry={nodes.MSIX370XPowerGamingTitatnum001.geometry} material={materials.darkgrey} />
          <mesh name="MSIX370XPowerGamingTitatnum001_1" geometry={nodes.MSIX370XPowerGamingTitatnum001_1.geometry} material={materials.MotherboardBaseFrontSide} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB" position={[-0.915, 2.01, -0.001]} scale={0}>
          <mesh name="Cube199" geometry={nodes.Cube199.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube199_1" geometry={nodes.Cube199_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB001" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB002" position={[-0.915, 2.01, -0.003]} scale={0}>
          <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube031_1" geometry={nodes.Cube031_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB003" position={[-0.915, 2.01, -0.004]} scale={0}>
          <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube032_1" geometry={nodes.Cube032_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB004" position={[-0.915, 2.01, -0.005]} scale={0}>
          <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube037_1" geometry={nodes.Cube037_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB005" position={[-0.915, 2.01, -0.006]} scale={0}>
          <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube038_1" geometry={nodes.Cube038_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB006" position={[-0.915, 2.01, -0.007]} scale={0}>
          <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube039_1" geometry={nodes.Cube039_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB007" position={[-0.915, 2.01, -0.008]} scale={0}>
          <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube040_1" geometry={nodes.Cube040_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB008" position={[-0.915, 2.01, -0.009]} scale={0}>
          <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube041_1" geometry={nodes.Cube041_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB009" position={[-0.915, 2.01, -0.0021]} scale={0}>
          <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube042_1" geometry={nodes.Cube042_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube303" geometry={nodes.Cube303.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube303_1" geometry={nodes.Cube303_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube303_2" geometry={nodes.Cube303_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz001" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube019_1" geometry={nodes.Cube019_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube019_2" geometry={nodes.Cube019_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz002" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube020_2" geometry={nodes.Cube020_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz003" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube021_2" geometry={nodes.Cube021_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz004" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube024_2" geometry={nodes.Cube024_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz005" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube025_2" geometry={nodes.Cube025_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz006" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube033_1" geometry={nodes.Cube033_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube033_2" geometry={nodes.Cube033_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz007" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube034_1" geometry={nodes.Cube034_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube034_2" geometry={nodes.Cube034_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz008" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube035_1" geometry={nodes.Cube035_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube035_2" geometry={nodes.Cube035_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz009" position={[-0.915, 2.01, -0.002]} scale={0}>
          <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube036_1" geometry={nodes.Cube036_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube036_2" geometry={nodes.Cube036_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="NvidiaGeForceRTX3090" position={[-0.433, 1.393, 1.179]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090_1" geometry={nodes.NvidiaGeForceRTX3090_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090_2" geometry={nodes.NvidiaGeForceRTX3090_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090_3" geometry={nodes.NvidiaGeForceRTX3090_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090_4" geometry={nodes.NvidiaGeForceRTX3090_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090_5" geometry={nodes.NvidiaGeForceRTX3090_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090_6" geometry={nodes.NvidiaGeForceRTX3090_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090_7" geometry={nodes.NvidiaGeForceRTX3090_7.geometry} material={materials['Material.002']} />
        </group>
        <group name="NvidiaGeForceRTX3090001" position={[-0.433, 1.193, 1.232]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090001_1" geometry={nodes.NvidiaGeForceRTX3090001_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090001_2" geometry={nodes.NvidiaGeForceRTX3090001_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090001_3" geometry={nodes.NvidiaGeForceRTX3090001_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090001_4" geometry={nodes.NvidiaGeForceRTX3090001_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090001_5" geometry={nodes.NvidiaGeForceRTX3090001_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090001_6" geometry={nodes.NvidiaGeForceRTX3090001_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090001_7" geometry={nodes.NvidiaGeForceRTX3090001_7.geometry} material={materials['Material.002']} />
        </group>
        <group name="NvidiaGeForceRTX3090002" position={[-0.433, 1.393, 1.139]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090002_1" geometry={nodes.NvidiaGeForceRTX3090002_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090002_2" geometry={nodes.NvidiaGeForceRTX3090002_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090002_3" geometry={nodes.NvidiaGeForceRTX3090002_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090002_4" geometry={nodes.NvidiaGeForceRTX3090002_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090002_5" geometry={nodes.NvidiaGeForceRTX3090002_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090002_6" geometry={nodes.NvidiaGeForceRTX3090002_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090002_7" geometry={nodes.NvidiaGeForceRTX3090002_7.geometry} material={materials['Material.002']} />
        </group>
        <group name="NvidiaGeForceRTX3090003" position={[-0.433, 1.393, 1.417]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090003_1" geometry={nodes.NvidiaGeForceRTX3090003_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090003_2" geometry={nodes.NvidiaGeForceRTX3090003_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090003_3" geometry={nodes.NvidiaGeForceRTX3090003_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090003_4" geometry={nodes.NvidiaGeForceRTX3090003_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090003_5" geometry={nodes.NvidiaGeForceRTX3090003_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090003_6" geometry={nodes.NvidiaGeForceRTX3090003_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090003_7" geometry={nodes.NvidiaGeForceRTX3090003_7.geometry} material={materials['Material.002']} />
        </group>
        <group name="NvidiaGeForceRTX3080" position={[-0.433, 1.016, 1.19]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080_1" geometry={nodes.NvidiaGeForceRTX3080_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080_2" geometry={nodes.NvidiaGeForceRTX3080_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080_3" geometry={nodes.NvidiaGeForceRTX3080_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080_4" geometry={nodes.NvidiaGeForceRTX3080_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080_5" geometry={nodes.NvidiaGeForceRTX3080_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080_6" geometry={nodes.NvidiaGeForceRTX3080_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080_7" geometry={nodes.NvidiaGeForceRTX3080_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080_8" geometry={nodes.NvidiaGeForceRTX3080_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3080001" position={[-0.433, 1.016, 1.19]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080001_1" geometry={nodes.NvidiaGeForceRTX3080001_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080001_2" geometry={nodes.NvidiaGeForceRTX3080001_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080001_3" geometry={nodes.NvidiaGeForceRTX3080001_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080001_4" geometry={nodes.NvidiaGeForceRTX3080001_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080001_5" geometry={nodes.NvidiaGeForceRTX3080001_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080001_6" geometry={nodes.NvidiaGeForceRTX3080001_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080001_7" geometry={nodes.NvidiaGeForceRTX3080001_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080001_8" geometry={nodes.NvidiaGeForceRTX3080001_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3080002" position={[-0.433, 1.016, 1.19]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080002_1" geometry={nodes.NvidiaGeForceRTX3080002_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080002_2" geometry={nodes.NvidiaGeForceRTX3080002_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080002_3" geometry={nodes.NvidiaGeForceRTX3080002_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080002_4" geometry={nodes.NvidiaGeForceRTX3080002_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080002_5" geometry={nodes.NvidiaGeForceRTX3080002_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080002_6" geometry={nodes.NvidiaGeForceRTX3080002_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080002_7" geometry={nodes.NvidiaGeForceRTX3080002_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080002_8" geometry={nodes.NvidiaGeForceRTX3080002_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3080003" position={[-0.433, 1.016, 1.19]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080003_1" geometry={nodes.NvidiaGeForceRTX3080003_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080003_2" geometry={nodes.NvidiaGeForceRTX3080003_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080003_3" geometry={nodes.NvidiaGeForceRTX3080003_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080003_4" geometry={nodes.NvidiaGeForceRTX3080003_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080003_5" geometry={nodes.NvidiaGeForceRTX3080003_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080003_6" geometry={nodes.NvidiaGeForceRTX3080003_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080003_7" geometry={nodes.NvidiaGeForceRTX3080003_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080003_8" geometry={nodes.NvidiaGeForceRTX3080003_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3070" position={[-0.702, 1.182, 0]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070_1" geometry={nodes.NvidiaGeForceRTX3070_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070_2" geometry={nodes.NvidiaGeForceRTX3070_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070_3" geometry={nodes.NvidiaGeForceRTX3070_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070_4" geometry={nodes.NvidiaGeForceRTX3070_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070_5" geometry={nodes.NvidiaGeForceRTX3070_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070_6" geometry={nodes.NvidiaGeForceRTX3070_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070_7" geometry={nodes.NvidiaGeForceRTX3070_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070_8" geometry={nodes.NvidiaGeForceRTX3070_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <group name="NvidiaGeForceRTX3070001" position={[-0.702, 1.49, 1.074]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070001_1" geometry={nodes.NvidiaGeForceRTX3070001_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070001_2" geometry={nodes.NvidiaGeForceRTX3070001_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070001_3" geometry={nodes.NvidiaGeForceRTX3070001_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070001_4" geometry={nodes.NvidiaGeForceRTX3070001_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070001_5" geometry={nodes.NvidiaGeForceRTX3070001_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070001_6" geometry={nodes.NvidiaGeForceRTX3070001_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070001_7" geometry={nodes.NvidiaGeForceRTX3070001_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070001_8" geometry={nodes.NvidiaGeForceRTX3070001_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <group name="NvidiaGeForceRTX3070002" position={[-0.702, 1.27, 0.944]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070002_1" geometry={nodes.NvidiaGeForceRTX3070002_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070002_2" geometry={nodes.NvidiaGeForceRTX3070002_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070002_3" geometry={nodes.NvidiaGeForceRTX3070002_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070002_4" geometry={nodes.NvidiaGeForceRTX3070002_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070002_5" geometry={nodes.NvidiaGeForceRTX3070002_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070002_6" geometry={nodes.NvidiaGeForceRTX3070002_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070002_7" geometry={nodes.NvidiaGeForceRTX3070002_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070002_8" geometry={nodes.NvidiaGeForceRTX3070002_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <group name="NvidiaGeForceRTX3070003" position={[-0.702, 1.27, 1.169]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070003_1" geometry={nodes.NvidiaGeForceRTX3070003_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070003_2" geometry={nodes.NvidiaGeForceRTX3070003_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070003_3" geometry={nodes.NvidiaGeForceRTX3070003_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070003_4" geometry={nodes.NvidiaGeForceRTX3070003_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070003_5" geometry={nodes.NvidiaGeForceRTX3070003_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070003_6" geometry={nodes.NvidiaGeForceRTX3070003_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070003_7" geometry={nodes.NvidiaGeForceRTX3070003_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070003_8" geometry={nodes.NvidiaGeForceRTX3070003_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <mesh name="Power_box?" geometry={nodes['Power_box?'].geometry} material={materials.BlackSurfice} position={[-0.882, 0.448, 0.015]} rotation={[0, -Math.PI / 2, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/pc_parts/pc_cases/CoolerMasterCaseMaker5t.glb')

export default CoolerMasterCaseMaker5t