/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CorsairAFSLIM120mm.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const CorsairAFSLIM120mm=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cooling/CorsairAFSLIM120mm.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={[1, 1, 0.616]}>
        <mesh geometry={nodes.Vert009.geometry} material={materials.WhiteMaterialImage} />
        <mesh geometry={nodes.Vert009_1.geometry} material={materials.FanWhite} />
      </group>
    </group>
  )
}

const CorsairAFSLIM120mmCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 10}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <CorsairAFSLIM120mm/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/cooling/CorsairAFSLIM120mm.glb')

export default CorsairAFSLIM120mmCanvas