/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CorsairICUELINKQX92mm.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const CorsairICUELINKQX92mm=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cooling/CorsairICUELINKQX92mm.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={0.655}>
        <mesh geometry={nodes.Vert013.geometry} material={materials.darkgrey} />
        <mesh geometry={nodes.Vert013_1.geometry} material={materials.CorsairIcon} />
      </group>
    </group>
  )
}

const CorsairICUELINKQX92mmCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 10}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <CorsairICUELINKQX92mm/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/cooling/CorsairICUELINKQX92mm.glb')

export default CorsairICUELINKQX92mmCanvas