/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CorsairAFSLIM92mm.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const CorsairAFSLIM92mm=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cooling/CorsairAFSLIM92mm.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={[0.767, 0.767, 0.472]}>
        <mesh geometry={nodes.Vert015.geometry} material={materials.WhiteMaterialImage} />
        <mesh geometry={nodes.Vert015_1.geometry} material={materials.FanWhite} />
      </group>
    </group>
  )
}

const CorsairAFSLIM92mmCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 10}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <CorsairAFSLIM92mm/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/cooling/CorsairAFSLIM92mm.glb')

export default CorsairAFSLIM92mmCanvas