/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CorsairAFSLIM140mm.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const CorsairAFSLIM140mm=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cooling/CorsairAFSLIM140mm.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={[1.166, 1.166, 0.718]}>
        <mesh geometry={nodes.Vert014.geometry} material={materials.WhiteMaterialImage} />
        <mesh geometry={nodes.Vert014_1.geometry} material={materials.FanWhite} />
      </group>
    </group>
  )
}

const CorsairAFSLIM140mmCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 10}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <CorsairAFSLIM140mm/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/cooling/CorsairAFSLIM140mm.glb')

export default CorsairAFSLIM140mmCanvas