/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CorsairICUELINKQX120mm.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const CorsairICUELINKQX120mm=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/cooling/CorsairICUELINKQX120mm.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, Math.PI]} scale={0.858}>
        <mesh geometry={nodes.Vert012.geometry} material={materials.darkgrey} />
        <mesh geometry={nodes.Vert012_1.geometry} material={materials.CorsairIcon} />
      </group>
    </group>
  )
}

const CorsairICUELINKQX120mmCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 10}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <CorsairICUELINKQX120mm/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/cooling/CorsairICUELINKQX120mm.glb')

export default CorsairICUELINKQX120mmCanvas