/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CorsairVengeance16gbDDR5.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF, Text } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const CorsairVengeance16gbDDR5=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/ram/CorsairVengeance16gbDDR5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube182.geometry} material={materials.VengeanceDDR5frontside} />
      <mesh geometry={nodes.Cube182_1.geometry} material={materials.VengeanceDDR5top} />
      <mesh geometry={nodes.Cube182_2.geometry} material={materials.VengeanceDDR5backside} />
      <mesh geometry={nodes.Cube182_3.geometry} material={materials.VengeanceDDR5backside} />
    </group>
  )
}

const CorsairVengeanceCanvas =()=>{
  return(
    <Canvas
      camera={{fov: 4.5}}>
      <Suspense>
        <ambientLight intensity={5} color={"red"}/>
        {/* <OrbitControls/> */}
        <Text fontSize={0.07} position={[0, 0, 1]}>NOT COMPATABLE</Text>
        <CorsairVengeance16gbDDR5 rotation-y={-1.57} position-y={0.03}/>
      </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/ram/CorsairVengeance16gbDDR5.glb')

export default CorsairVengeanceCanvas