/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 CX550Powerunit.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const CX550Powerunit =(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/power_units/CX550Powerunit.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.207, 0]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Torus007.geometry} material={materials.darkgrey} />
        <mesh geometry={nodes.Torus007_1.geometry} material={materials.CX550Top} />
        <mesh geometry={nodes.Torus007_2.geometry} material={materials.CX550Front} />
        <mesh geometry={nodes.Torus007_3.geometry} material={materials.CX550Side} />
        <mesh geometry={nodes.Torus007_4.geometry} material={materials.CX550Back} />
        <mesh geometry={nodes.Torus007_5.geometry} material={materials.PowerBox1200top} />
        <mesh geometry={nodes.Torus007_6.geometry} material={materials.PowerBoxHX1200back} />
        <mesh geometry={nodes.Torus007_7.geometry} material={materials.PowerBoxHX1200front} />
        <mesh geometry={nodes.Torus007_8.geometry} material={materials['PowerBoxHX1200front.001']} />
      </group>
    </group>
  )
}

const CX550PowerunitCanvas=()=>{
  return(
    <Canvas 
      camera={{fov: 8}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <CX550Powerunit/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/power_units/CX550Powerunit.glb')

export default CX550PowerunitCanvas