/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 HX1200Powerunit.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const HX1200Powerunit=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/power_units/HX1200Powerunit.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.142, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.929}>
        <mesh geometry={nodes.Plane065.geometry} material={materials.PowerBox1200top} />
        <mesh geometry={nodes.Plane065_1.geometry} material={materials.PowerBoxHX1200back} />
        <mesh geometry={nodes.Plane065_2.geometry} material={materials.PowerBoxHX1200front} />
        <mesh geometry={nodes.Plane065_3.geometry} material={materials.PowerBoxHX1200side} />
        <mesh geometry={nodes.Plane065_4.geometry} material={materials.BlackMetalic} />
        <mesh geometry={nodes.Plane065_5.geometry} material={materials.darkgrey} />
      </group>
    </group>
  )
}

const HX1200PowerunitCanvas = () =>{
  return(
    <Canvas
     camera={{fov: 8}}>
      <Suspense>
        <ambientLight intensity={2} color={"white"}/>
        <OrbitControls/>
        <HX1200Powerunit/>
      </Suspense>
     </Canvas>
  )
}

useGLTF.preload('/pc_parts/power_units/HX1200Powerunit.glb')

export default HX1200PowerunitCanvas