/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 HX850Powerunit.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const HX850Powerunit=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/power_units/HX850Powerunit.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.132, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.929}>
        <mesh geometry={nodes.Plane020.geometry} material={materials.PowerBox1200top} />
        <mesh geometry={nodes.Plane020_1.geometry} material={materials.PowerBoxHX1200back} />
        <mesh geometry={nodes.Plane020_2.geometry} material={materials.PowerBoxHX1200front} />
        <mesh geometry={nodes.Plane020_3.geometry} material={materials.BlackMetalic} />
        <mesh geometry={nodes.Plane020_4.geometry} material={materials.PowerBoxHX850side} />
        <mesh geometry={nodes.Plane020_5.geometry} material={materials.PowerBoxHX850back} />
        <mesh geometry={nodes.Plane020_6.geometry} material={materials.darkgrey} />
      </group>
    </group>
  )
}

const HX850PowerunitCanvas =()=>{
  return(
    <Canvas
      camera={{fov: 8}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <HX850Powerunit/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/power_units/HX850Powerunit.glb')

export default HX850PowerunitCanvas