/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 MSIX370XPowerGamingTitatnum.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const MSIX370XPowerGamingTitatnum=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/motherboards/MSIX370XPowerGamingTitatnum.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.078}>
        <mesh geometry={nodes.MSIX370XPowerGamingTitatnum_1.geometry} material={materials.darkgrey} />
        <mesh geometry={nodes.MSIX370XPowerGamingTitatnum_2.geometry} material={materials.MotherboardBaseFrontSide} />
        <mesh geometry={nodes.MSIX370XPowerGamingTitatnum_3.geometry} material={materials.MotherboardBaseBackSide} />
        <mesh geometry={nodes.MSIX370XPowerGamingTitatnum_4.geometry} material={materials.MetallicGrey} />
        <mesh geometry={nodes.MSIX370XPowerGamingTitatnum_5.geometry} material={materials.red} />
        <mesh geometry={nodes.MSIX370XPowerGamingTitatnum_6.geometry} material={materials.gold} />
        <mesh geometry={nodes.MSIX370XPowerGamingTitatnum_7.geometry} material={materials.lightdarkgrey} />
      </group>
    </group>
  )
}

const MSIX370XPowerGamingTitatnumCanvas=()=>{
  return(
    <Canvas
    camera={{fov: 20}}>
      <Suspense>
        <ambientLight intensity={2} color={"white"}/>
        <OrbitControls/>
        <MSIX370XPowerGamingTitatnum rotation-y={4.7} position-y={-0.1}/>
      </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/motherboards/MSIX370XPowerGamingTitatnum.glb')

export default MSIX370XPowerGamingTitatnumCanvas