/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 PhanteksEclipseP300Midtower.glb 
*/

import React, { useContext, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { AnimationContext } from '../../App'
import { playAnimation, stopAnimation } from '../componentLogic/AnimationLogic'

const PhanteksEclipseP300Midtower=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/pc_parts/pc_cases/PhanteksEclipseP300Midtower.glb')
  const { actions } = useAnimations(animations, group)

    const { medCaseSide1Slide, setMedCaseSide1Slide,
    lCaseBigMBSlide, setLCaseBigMBSlide,
    lCaseMedMBSlide, setLCaseMedMBSlide,
    lCaseSmlMBSlide, setLCaseSmlMBSlide,
    amdRyzen5BIGMB, setAMDRyzen5BIGMB,
    amdRyzen7BIGMB, setAMDRyzen7BIGMB,
    amdRyzen9BIGMB, setAMDRyzen9BIGMB,
    amdRyzen5MEDMB, setAMDRyzen5MEDMB,
    amdRyzen7MEDMB, setAMDRyzen7MEDMB,
    amdRyzen9MEDMB, setAMDRyzen9MEDMB,
    amdRyzen5SMLMB, setAMDRyzen5SMLMB,
    amdRyzen7SMLMB, setAMDRyzen7SMLMB,
    amdRyzen9SMLMB, setAMDRyzen9SMLMB,
    RTX3070BIGMBtop, setRTX3070BIGMBtop,
    RTX3070BIGMBbot, setRTX3070BIGMBbot,
    RTX3080BIGMBtop, setRTX3080BIGMBtop,
    RTX3080BIGMBbot, setRTX3080BIGMBbot,
    RTX3090BIGMBtop, setRTX3090BIGMBtop,
    RTX3090BIGMBbot, setRTX3090BIGMBbot,
    RTX3070MEDMB, setRTX3070MEDMB,
    RTX3080MEDMB, setRTX3080MEDMB,
    RTX3090MEDMB, setRTX3090MEDMB,
    RTX3070SMLMB, setRTX3070SMLMB,
    RTX3080SMLMB, setRTX3080SMLMB,
    RTX3090SMLMB, setRTX3090SMLMB,
    HPV8GBRAMBIGMBslot1, setHPV8GBRAMBIGMBslot1,
    HPV8GBRAMBIGMBslot2, setHPV8GBRAMBIGMBslot2,
    HPV8GBRAMBIGMBslot3, setHPV8GBRAMBIGMBslot3,
    HPV8GBRAMBIGMBslot4, setHPV8GBRAMBIGMBslot4,
    KFBeast16BGRAMBIGMBslot1, setKFBeast16BGRAMBIGMBslot1,
    KFBeast16BGRAMBIGMBslot2, setKFBeast16BGRAMBIGMBslot2,
    KFBeast16BGRAMBIGMBslot3, setKFBeast16BGRAMBIGMBslot3,
    KFBeast16BGRAMBIGMBslot4, setKFBeast16BGRAMBIGMBslot4,
    HPV8GBRAMMEDMBslot1, setHPV8GBRAMMEDMBslot1,
    HPV8GBRAMMEDMBslot2, setHPV8GBRAMMEDMBslot2,
    HPV8GBRAMMEDMBslot3, setHPV8GBRAMMEDMBslot3,
    HPV8GBRAMMEDMBslot4, setHPV8GBRAMMEDMBslot4,
    KFBeast16BGRAMMEDMBslot1, setKFBeast16BGRAMMEDMBslot1,
    KFBeast16BGRAMMEDMBslot2, setKFBeast16BGRAMMEDMBslot2,
    KFBeast16BGRAMMEDMBslot3, setKFBeast16BGRAMMEDMBslot3,
    KFBeast16BGRAMMEDMBslot4, setKFBeast16BGRAMMEDMBslot4,
    HPV8GBRAMSMLMBslot1, setHPV8GBRAMSMLMBslot1,
    HPV8GBRAMSMLMBslot2, setHPV8GBRAMSMLMBslot2,
    KFBeast16BGRAMSMLMBslot1, setKFBeast16BGRAMSMLMBslot1,
    KFBeast16BGRAMSMLMBslot2, setKFBeast16BGRAMSMLMBslot2,
    beast8GBRam, setbeast8GBRam,
    HP16BGRam, setHP16BGRam,
    CX550PowerunitBIG, setCX550PowerunitBIG,
    HX850PowerunitBIG, setHX850PowerunitBIG,
    HX1200PowerunitBIG, setHX1200PowerunitBIG,
    Samsung870EVOBIGs, setSamsung870EVOBIGs,
    Samsung970SlotsBIGSlot1, setSamsung970SlotsBIGSlot1,
    Samsung970SlotsBIGSlot2, setSamsung970SlotsBIGSlot2,
    Samsung970SlotsMED, setSamsung970SlotsMED,
    SeagateBarraCuda2TBBIGs, setSeagateBarraCuda2TBBIGs,
    CorsairAFSLIMBIGs, setCorsairAFSLIMBIGs,
    CorsairICUELINKQXBIGs, setCorsairICUELINKQXBIGs,
    CorsairAFELITEBIGs, setCorsairAFELITEBIGs } = useContext(AnimationContext)


  useEffect(() => {
    if (medCaseSide1Slide) {
      playAnimation(actions.SidePanel1Slide)
      playAnimation(actions.SidePanel2Slide)
    } else if (medCaseSide1Slide == false) {
      stopAnimation(actions.SidePanel1Slide)
      stopAnimation(actions.SidePanel2Slide)
    }
    if (lCaseBigMBSlide == false && lCaseMedMBSlide == false && lCaseSmlMBSlide == false) {
      setbeast8GBRam(false)
      setHP16BGRam(false)
      setCX550PowerunitBIG(false)
      setHX850PowerunitBIG(false)
      setHX1200PowerunitBIG(false)
    }
    if (lCaseBigMBSlide) {
      playAnimation(actions.MSIX370XPowerGamingTitatnumMoving)
    } else if (lCaseBigMBSlide == false) {
      stopAnimation(actions.MSIX370XPowerGamingTitatnumMoving)
      setAMDRyzen5BIGMB(false)
      setAMDRyzen7BIGMB(false)
      setAMDRyzen9BIGMB(false)
      setRTX3070BIGMBtop(false)
      setRTX3070BIGMBbot(false)
      setRTX3080BIGMBtop(false)
      setRTX3080BIGMBbot(false)
      setRTX3090BIGMBtop(false)
      setRTX3090BIGMBbot(false)
      setHPV8GBRAMBIGMBslot1(false)
      setHPV8GBRAMBIGMBslot2(false)
      setHPV8GBRAMBIGMBslot3(false)
      setHPV8GBRAMBIGMBslot4(false)
      setKFBeast16BGRAMBIGMBslot1(false)
      setKFBeast16BGRAMBIGMBslot2(false)
      setKFBeast16BGRAMBIGMBslot3(false)
      setKFBeast16BGRAMBIGMBslot4(false)
      setSamsung970SlotsBIGSlot1(false)
      setSamsung970SlotsBIGSlot2(false)
    }
    if (lCaseMedMBSlide) {
      playAnimation(actions.AsusEXA320MSlide)
    } else if (lCaseMedMBSlide == false) {
      stopAnimation(actions.AsusEXA320MSlide)
      setAMDRyzen5MEDMB(false)
      setAMDRyzen7MEDMB(false)
      setAMDRyzen9MEDMB(false)
      setRTX3070MEDMB(false)
      setRTX3080MEDMB(false)
      setRTX3090MEDMB(false)
      setHPV8GBRAMMEDMBslot1(false)
      setHPV8GBRAMMEDMBslot2(false)
      setHPV8GBRAMMEDMBslot3(false)
      setHPV8GBRAMMEDMBslot4(false)
      setKFBeast16BGRAMMEDMBslot1(false)
      setKFBeast16BGRAMMEDMBslot2(false)
      setKFBeast16BGRAMMEDMBslot3(false)
      setKFBeast16BGRAMMEDMBslot4(false)
    }
    if (lCaseSmlMBSlide) {
      playAnimation(actions.AsusRogStrixB350ISlide)
    } else if (lCaseSmlMBSlide == false) {
      stopAnimation(actions.AsusRogStrixB350ISlide)
      setAMDRyzen5SMLMB(false)
      setAMDRyzen7SMLMB(false)
      setAMDRyzen9SMLMB(false)
      setRTX3070SMLMB(false)
      setRTX3080SMLMB(false)
      setRTX3090SMLMB(false)
      setHPV8GBRAMSMLMBslot1(false)
      setHPV8GBRAMSMLMBslot2(false)
      setKFBeast16BGRAMSMLMBslot1(false)
      setKFBeast16BGRAMSMLMBslot2(false)
      setSamsung970SlotsMED(false)
    }
    if (amdRyzen5BIGMB) {
      playAnimation(actions.AMDRyzen5BIGMB)
    } else if (amdRyzen5BIGMB == false) {
      stopAnimation(actions.AMDRyzen5BIGMB)
    }
    if (amdRyzen7BIGMB) {
      playAnimation(actions.AMDRyzen7BIGMB)
    } else if (amdRyzen7BIGMB == false) {
      stopAnimation(actions.AMDRyzen7BIGMB)
    }
    if (amdRyzen9BIGMB) {
      playAnimation(actions.AMDRyzen9BIGMB)
    } else if (amdRyzen9BIGMB == false) {
      stopAnimation(actions.AMDRyzen9BIGMB)
    }
    if (amdRyzen5MEDMB) {
      playAnimation(actions.AMDRyzen5MEDMB)
    } else if (amdRyzen5MEDMB == false) {
      stopAnimation(actions.AMDRyzen5MEDMB)
    }
    if (amdRyzen7MEDMB) {
      playAnimation(actions.AMDRyzen7MEDMB)
    } else if (amdRyzen7MEDMB == false) {
      stopAnimation(actions.AMDRyzen7MEDMB)
    }
    if (amdRyzen9MEDMB) {
      playAnimation(actions.AMDRyzen9MEDMB)
    } else if (amdRyzen9MEDMB == false) {
      stopAnimation(actions.AMDRyzen9MEDMB)
    }
    if (amdRyzen5SMLMB) {
      playAnimation(actions.AMDRyzen5SMLMB)
    } else if (amdRyzen5SMLMB == false) {
      stopAnimation(actions.AMDRyzen5SMLMB)
    }
    if (amdRyzen7SMLMB) {
      playAnimation(actions.AMDRyzen7SMLMB)
    } else if (amdRyzen7SMLMB == false) {
      stopAnimation(actions.AMDRyzen7SMLMB)
    }
    if (amdRyzen9SMLMB) {
      playAnimation(actions.AMDRyzen9SMLMB)
    } else if (amdRyzen9SMLMB == false) {
      stopAnimation(actions.AMDRyzen9SMLMB)
    }

    if (RTX3070BIGMBtop) {
      playAnimation(actions.RTX3070BIGMBSlot1)
    } else if (RTX3070BIGMBtop == false) {
      (actions.RTX3070BIGMBSlot1)
    }
    if (RTX3070BIGMBbot) {
      playAnimation(actions.RTX3070BIGMBSlot2)
    } else if (RTX3070BIGMBbot == false) {
      stopAnimation(actions.RTX3070BIGMBSlot2)
    }
    if (RTX3070MEDMB) {
      playAnimation(actions.RTX3070MEDMB)
    } else if (RTX3070MEDMB == false) {
      stopAnimation(actions.RTX3070MEDMB)
    }
    if (RTX3070SMLMB) {
      playAnimation(actions.RTX3070SMLMB)
    } else if (RTX3070SMLMB == false) {
      stopAnimation(actions.RTX3070SMLMB)
    }
    if (RTX3080BIGMBtop) {
      playAnimation(actions.RTX3080BIGMBSlot1)
    } else if (RTX3080BIGMBtop == false) {
      stopAnimation(actions.RTX3080BIGMBSlot1)
    }
    if (RTX3080BIGMBbot) {
      playAnimation(actions.RTX3080BIGMBSlot2)
    } else if (RTX3080BIGMBbot == false) {
      stopAnimation(actions.RTX3080BIGMBSlot2)
    }
    if (RTX3080MEDMB) {
      playAnimation(actions.RTX3080MEDMB)
    } else if (RTX3080MEDMB == false) {
      stopAnimation(actions.RTX3080MEDMB)
    }
    if (RTX3080SMLMB) {
      playAnimation(actions.RTX3080SMLMB)
    } else if (RTX3080SMLMB == false) {
      stopAnimation(actions.RTX3080SMLMB)
    }
    if (RTX3090BIGMBtop) {
      playAnimation(actions.RTX3090BIGMBSlot1)
    } else if (RTX3090BIGMBtop == false) {
      stopAnimation(actions.RTX3090BIGMBSlot1)
    }
    if (RTX3090BIGMBbot) {
      playAnimation(actions.RTX3090BIGMBSlot2)
    } else if (RTX3090BIGMBbot == false) {
      stopAnimation(actions.RTX3090BIGMBSlot2)
    }
    if (RTX3090MEDMB) {
      playAnimation(actions.RTX3090MEDMB)
    } else if (RTX3090MEDMB == false) {
      stopAnimation(actions.RTX3090MEDMB)
    }
    if (RTX3090SMLMB) {
      playAnimation(actions.RTX3090SMLMB)
    } else if (RTX3090SMLMB == false) {
      stopAnimation(actions.RTX3090SMLMB)
    }

    if (HPV8GBRAMBIGMBslot1) {
      playAnimation(actions.DIMM16GBBIGMBSlot1)
    } else {
      stopAnimation(actions.DIMM16GBBIGMBSlot1)
    }
    if (HPV8GBRAMBIGMBslot2) {
      playAnimation(actions.DIMM16GBBIGMBSlot2)
    } else {
      stopAnimation(actions.DIMM16GBBIGMBSlot2)
    }
    if (HPV8GBRAMBIGMBslot3) {
      playAnimation(actions.DIMM16GBBIGMBSlot3)
    } else {
      stopAnimation(actions.DIMM16GBBIGMBSlot3)
    }
    if (HPV8GBRAMBIGMBslot4) {
      playAnimation(actions.DIMM16GBBIGMBSlot4)
    } else {
      stopAnimation(actions.DIMM16GBBIGMBSlot4)
    }
    if (HPV8GBRAMMEDMBslot1) {
      playAnimation(actions.DIMM16GBMEDMBSlot1)
    } else {
      stopAnimation(actions.DIMM16GBMEDMBSlot1)
    }
    if (HPV8GBRAMMEDMBslot2) {
      playAnimation(actions.DIMM16GBMEDMBSlot2)
    } else {
      stopAnimation(actions.DIMM16GBMEDMBSlot2)
    }
    if (HPV8GBRAMMEDMBslot3) {
      playAnimation(actions.DIMM16GBMEDMBSlot3)
    } else {
      stopAnimation(actions.DIMM16GBMEDMBSlot3)
    }
    if (HPV8GBRAMMEDMBslot4) {
      playAnimation(actions.DIMM16GBMEDMBSlot4)
    } else {
      stopAnimation(actions.DIMM16GBMEDMBSlot4)
    }
    if (HPV8GBRAMSMLMBslot1) {
      playAnimation(actions.DIMM16GBSMLMBSlot1)
    } else {
      stopAnimation(actions.DIMM16GBSMLMBSlot1)
    }
    if (HPV8GBRAMSMLMBslot2) {
      playAnimation(actions.DIMM16GBSMLMBSlot2)
    } else {
      stopAnimation(actions.DIMM16GBSMLMBSlot2)
    }

    if (KFBeast16BGRAMBIGMBslot1) {
      playAnimation(actions.KingstonFury8BGBIGMBSlot1)
    } else {
      stopAnimation(actions.KingstonFury8BGBIGMBSlot1)
    }
    if (KFBeast16BGRAMBIGMBslot2) {
      playAnimation(actions.KingstonFury8BGBIGMBSlot2)
    } else {
      stopAnimation(actions.KingstonFury8BGBIGMBSlot2)
    }
    if (KFBeast16BGRAMBIGMBslot3) {

      playAnimation(actions.KingstonFury8BGBIGMBSlot3)
    } else {
      stopAnimation(actions.KingstonFury8BGBIGMBSlot3)
    }
    if (KFBeast16BGRAMBIGMBslot4) {

      playAnimation(actions.KingstonFury8BGBIGMBSlot4)
    } else {
      stopAnimation(actions.KingstonFury8BGBIGMBSlot4)
    }
    if (KFBeast16BGRAMMEDMBslot1) {
      playAnimation(actions.KingstonFury8BGMEDMBSlot1)
    } else {
      stopAnimation(actions.KingstonFury8BGMEDMBSlot1)
    }
    if (KFBeast16BGRAMMEDMBslot2) {
      playAnimation(actions.KingstonFury8BGMEDMBSlot2)
    } else {
      stopAnimation(actions.KingstonFury8BGMEDMBSlot2)
    }
    if (KFBeast16BGRAMMEDMBslot3) {
      playAnimation(actions.KingstonFury8BGMEDMBSlot3)
    } else {
      stopAnimation(actions.KingstonFury8BGMEDMBSlot3)
    }
    if (KFBeast16BGRAMMEDMBslot4) {
      playAnimation(actions.KingstonFury8BGMEDMBSlot4)
    } else {
      stopAnimation(actions.KingstonFury8BGMEDMBSlot4)
    }
    if (KFBeast16BGRAMSMLMBslot1) {
      playAnimation(actions.KingstonFury8BGSMLMBSlot1)
    } else {
      stopAnimation(actions.KingstonFury8BGSMLMBSlot1)
    }
    if (KFBeast16BGRAMSMLMBslot2) {
      playAnimation(actions.KingstonFury8BGSMLMBSlot2)
    } else {
      stopAnimation(actions.KingstonFury8BGSMLMBSlot2)
    }

    if (Samsung870EVOBIGs[0].slot == true) {
      playAnimation(actions.Samsung870EVOSlot1)
    } else {
      stopAnimation(actions.Samsung870EVOSlot1)
    }
    if (Samsung870EVOBIGs[1].slot == true) {
      playAnimation(actions.Samsung870EVOSlot2)
    } else {
      stopAnimation(actions.Samsung870EVOSlot2)
    }

    
    if (Samsung970SlotsBIGSlot1) {
      playAnimation(actions.Samsung970EVOPlusBIGMBSlot1)

    } else {
      stopAnimation(actions.Samsung970EVOPlusBIGMBSlot1)
    }
    if (Samsung970SlotsBIGSlot2) {
      playAnimation(actions.Samsung970EVOPlusBIGMBSlot2)
      playAnimation(actions.MSIX370XPowerGamingTitatnumSHIELD)
    } else {
      stopAnimation(actions.Samsung970EVOPlusBIGMBSlot2)
      stopAnimation(actions.MSIX370XPowerGamingTitatnumSHIELD)
    }
    if (Samsung970SlotsMED) {
      playAnimation(actions.Samsung970EVOPlusMEDMB)
    } else {
      stopAnimation(actions.Samsung970EVOPlusMEDMB)
    }

    if (SeagateBarraCuda2TBBIGs[0].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot1)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot1)
    }
    if (SeagateBarraCuda2TBBIGs[1].slot == true) {
      playAnimation(actions.SeagateBarraCuda2TBSlot2)
    } else {
      stopAnimation(actions.SeagateBarraCuda2TBSlot2)
    }

    if (CX550PowerunitBIG) {
      playAnimation(actions.CX550PowerUnitSlide)
    } else {
      stopAnimation(actions.CX550PowerUnitSlide)
    }
    if (HX850PowerunitBIG) {
      playAnimation(actions.HX850PowerUnitSlide)
    } else {
      stopAnimation(actions.HX850PowerUnitSlide)
    }
    if (HX1200PowerunitBIG) {
      playAnimation(actions.HX1200PowerUnitSlide)
    } else {
      stopAnimation(actions.HX1200PowerUnitSlide)
    }
    
    
  }, [medCaseSide1Slide,
    lCaseBigMBSlide, lCaseMedMBSlide, lCaseSmlMBSlide,
    amdRyzen5BIGMB, amdRyzen7BIGMB, amdRyzen9BIGMB,
    amdRyzen5MEDMB, amdRyzen7MEDMB, amdRyzen9MEDMB,
    amdRyzen5SMLMB, amdRyzen7SMLMB, amdRyzen9SMLMB,
    RTX3070BIGMBtop, RTX3070BIGMBbot, RTX3070MEDMB, RTX3070SMLMB,
    RTX3080BIGMBtop, RTX3080BIGMBbot, RTX3080MEDMB, RTX3080SMLMB,
    RTX3090BIGMBtop, RTX3090BIGMBbot, RTX3090MEDMB, RTX3090SMLMB,
    HPV8GBRAMBIGMBslot1, HPV8GBRAMBIGMBslot2, HPV8GBRAMBIGMBslot3, HPV8GBRAMBIGMBslot4,
    HPV8GBRAMMEDMBslot1, HPV8GBRAMMEDMBslot2, HPV8GBRAMMEDMBslot3, HPV8GBRAMMEDMBslot4,
    HPV8GBRAMSMLMBslot1, HPV8GBRAMSMLMBslot2,
    KFBeast16BGRAMBIGMBslot1, KFBeast16BGRAMBIGMBslot2, KFBeast16BGRAMBIGMBslot3, KFBeast16BGRAMBIGMBslot4,
    KFBeast16BGRAMMEDMBslot1, KFBeast16BGRAMMEDMBslot2, KFBeast16BGRAMMEDMBslot3, KFBeast16BGRAMMEDMBslot4,
    KFBeast16BGRAMSMLMBslot1, KFBeast16BGRAMSMLMBslot2,
    CX550PowerunitBIG, HX850PowerunitBIG, HX1200PowerunitBIG,
    Samsung870EVOBIGs, Samsung970SlotsBIGSlot1, Samsung970SlotsBIGSlot2, Samsung970SlotsMED,
    SeagateBarraCuda2TBBIGs, CorsairAFSLIMBIGs, CorsairICUELINKQXBIGs, CorsairAFELITEBIGs])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube" position={[-0.141, -0.246, -0.229]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.darkgrey} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.red} />
          <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.MetallicGrey} />
          <mesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials.DarkBlue} />
        </group>
        <group name="Cube001">
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.darkgrey} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.red} />
        </group>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.darkgrey} />
        <group name="Cube003">
          <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.darkgrey} />
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials.red} />
        </group>
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.darkgrey} position={[-1.019, -0.247, 0.203]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.darkgrey} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.darkgrey} position={[0.343, -0.822, -0.065]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.darkgrey} position={[0.523, -0.807, 0.005]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.darkgrey} position={[0.529, -0.962, 0.005]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.darkgrey} position={[0.645, -1.093, 0]} scale={[-0.077, -0.033, -0.077]} />
        <mesh name="TopSmallGrid" geometry={nodes.TopSmallGrid.geometry} material={materials.darkgrey} position={[-0.388, 1.126, -0.003]} />
        <mesh name="TopBigGrid" geometry={nodes.TopBigGrid.geometry} material={materials.darkgrey} position={[-0.388, 1.128, -0.003]} />
        <mesh name="TopSmallGridFrame" geometry={nodes.TopSmallGridFrame.geometry} material={materials.darkgrey} />
        <mesh name="Vert005" geometry={nodes.Vert005.geometry} material={materials.darkgrey} position={[-1.035, 0.134, 0.19]} rotation={[0, 0, -Math.PI / 2]} scale={[0.564, 0.564, 0.637]} />
        <group name="CorsairFanBlackv1_120mm005" position={[-0.959, 0.617, 0.166]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Vert012" geometry={nodes.Vert012.geometry} material={materials.darkgrey} />
          <mesh name="Vert012_1" geometry={nodes.Vert012_1.geometry} material={materials['Material.003']} />
        </group>
        <group name="AsusEX-A320M-Gaming" position={[-0.242, 0.333, 1.856]} scale={0}>
          <mesh name="AsusEX-A320M-Gaming_1" geometry={nodes['AsusEX-A320M-Gaming_1'].geometry} material={materials.darkgrey} />
          <mesh name="AsusEX-A320M-Gaming_2" geometry={nodes['AsusEX-A320M-Gaming_2'].geometry} material={materials.gold} />
          <mesh name="AsusEX-A320M-Gaming_3" geometry={nodes['AsusEX-A320M-Gaming_3'].geometry} material={materials['AsusEX-A320-GamingFrontSide']} />
          <mesh name="AsusEX-A320M-Gaming_4" geometry={nodes['AsusEX-A320M-Gaming_4'].geometry} material={materials['AsusEX-A320-GamingBackSide']} />
          <mesh name="AsusEX-A320M-Gaming_5" geometry={nodes['AsusEX-A320M-Gaming_5'].geometry} material={materials.MetallicGrey} />
          <mesh name="AsusEX-A320M-Gaming_6" geometry={nodes['AsusEX-A320M-Gaming_6'].geometry} material={materials.lightpurple} />
          <mesh name="AsusEX-A320M-Gaming_7" geometry={nodes['AsusEX-A320M-Gaming_7'].geometry} material={materials.cyan} />
          <mesh name="AsusEX-A320M-Gaming_8" geometry={nodes['AsusEX-A320M-Gaming_8'].geometry} material={materials.lightred} />
          <mesh name="AsusEX-A320M-Gaming_9" geometry={nodes['AsusEX-A320M-Gaming_9'].geometry} material={materials.lightdarkgrey} />
          <mesh name="AsusEX-A320M-Gaming_10" geometry={nodes['AsusEX-A320M-Gaming_10'].geometry} material={materials.DarkBlue} />
          <mesh name="AsusEX-A320M-Gaming_11" geometry={nodes['AsusEX-A320M-Gaming_11'].geometry} material={materials.red} />
          <mesh name="AsusEX-A320M-Gaming_12" geometry={nodes['AsusEX-A320M-Gaming_12'].geometry} material={materials['AsusRogStrixB350-IBase']} />
          <mesh name="AsusEX-A320M-Gaming_13" geometry={nodes['AsusEX-A320M-Gaming_13'].geometry} material={materials.softred} />
          <mesh name="AsusEX-A320M-Gaming_14" geometry={nodes['AsusEX-A320M-Gaming_14'].geometry} material={materials.lightgreen} />
          <mesh name="AsusEX-A320M-Gaming_15" geometry={nodes['AsusEX-A320M-Gaming_15'].geometry} material={materials.skyblue} />
          <mesh name="AsusEX-A320M-Gaming_16" geometry={nodes['AsusEX-A320M-Gaming_16'].geometry} material={materials.WhiteMaterialImage} />
          <mesh name="AsusEX-A320M-Gaming_17" geometry={nodes['AsusEX-A320M-Gaming_17'].geometry} material={materials.MotherboardBaseFrontSide} />
        </group>
        <group name="SeagateBarraCuda2TB" position={[1.353, -0.801, 0.863]} scale={0}>
          <mesh name="Cube598" geometry={nodes.Cube598.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube598_1" geometry={nodes.Cube598_1.geometry} material={materials.darkgrey} />
          <mesh name="Cube598_2" geometry={nodes.Cube598_2.geometry} material={materials.MetallicGrey} />
          <mesh name="Cube598_3" geometry={nodes.Cube598_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube598_4" geometry={nodes.Cube598_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="SeagateBarraCuda2TB001" position={[1.353, -0.958, 0.863]} scale={0}>
          <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Cube027_1" geometry={nodes.Cube027_1.geometry} material={materials.darkgrey} />
          <mesh name="Cube027_2" geometry={nodes.Cube027_2.geometry} material={materials.MetallicGrey} />
          <mesh name="Cube027_3" geometry={nodes.Cube027_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
          <mesh name="Cube027_4" geometry={nodes.Cube027_4.geometry} material={materials.SeagateBarraCuda2TBback} />
        </group>
        <group name="Samsung970EVOPlus" position={[-0.794, -0.056, -0.253]} scale={0}>
          <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.Samsung970EVOPlusfront} />
          <mesh name="Plane008_1" geometry={nodes.Plane008_1.geometry} material={materials.Samsung970EVOPlusback} />
          <mesh name="Plane008_2" geometry={nodes.Plane008_2.geometry} material={materials.darkgrey} />
        </group>
        <group name="Samsung970EVOPlus001" position={[-0.794, -0.354, -0.253]} scale={0}>
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Samsung970EVOPlusfront} />
          <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials.Samsung970EVOPlusback} />
          <mesh name="Plane002_2" geometry={nodes.Plane002_2.geometry} material={materials.darkgrey} />
        </group>
        <group name="Samsung970EVOPlus002" position={[-0.794, -0.05, -0.253]} scale={0}>
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.Samsung970EVOPlusfront} />
          <mesh name="Plane006_1" geometry={nodes.Plane006_1.geometry} material={materials.Samsung970EVOPlusback} />
          <mesh name="Plane006_2" geometry={nodes.Plane006_2.geometry} material={materials.darkgrey} />
        </group>
        <group name="Samsung870EVO" position={[1.201, -0.807, 0.966]} scale={0}>
          <mesh name="Samsung870EVO_1" geometry={nodes.Samsung870EVO_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO_2" geometry={nodes.Samsung870EVO_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <group name="Samsung870EVO001" position={[1.201, -0.963, 0.966]} scale={0}>
          <mesh name="Samsung870EVO001_1" geometry={nodes.Samsung870EVO001_1.geometry} material={materials.Samsung870EVO_back} />
          <mesh name="Samsung870EVO001_2" geometry={nodes.Samsung870EVO001_2.geometry} material={materials.Samsung870EVO_front} />
        </group>
        <mesh name="AMDRyzen9-5950x" geometry={nodes['AMDRyzen9-5950x'].geometry} material={materials['AMDRyzen9-5950x']} position={[-0.828, 0.627, -0.195]} scale={0} />
        <mesh name="AMDRyzen7-5700" geometry={nodes['AMDRyzen7-5700'].geometry} material={materials['AMDRyzen7-5700']} position={[-0.828, 0.627, -0.195]} scale={0} />
        <mesh name="AMDRyzen5-5600" geometry={nodes['AMDRyzen5-5600'].geometry} material={materials['AMDRyzen5-5600']} position={[-0.828, 0.627, -0.195]} scale={0} />
        <mesh name="AMDRyzen5-5600001" geometry={nodes['AMDRyzen5-5600001'].geometry} material={materials['AMDRyzen5-5600']} position={[-0.533, 0.547, -0.281]} scale={0} />
        <mesh name="AMDRyzen5-5600002" geometry={nodes['AMDRyzen5-5600002'].geometry} material={materials['AMDRyzen5-5600']} position={[-0.557, 0.554, -0.176]} scale={0} />
        <mesh name="AMDRyzen7-5700001" geometry={nodes['AMDRyzen7-5700001'].geometry} material={materials['AMDRyzen7-5700']} position={[-0.533, 0.547, -0.281]} scale={0} />
        <mesh name="AMDRyzen7-5700002" geometry={nodes['AMDRyzen7-5700002'].geometry} material={materials['AMDRyzen7-5700']} position={[-0.557, 0.554, -0.176]} scale={0} />
        <mesh name="AMDRyzen9-5950x001" geometry={nodes['AMDRyzen9-5950x001'].geometry} material={materials['AMDRyzen9-5950x']} position={[-0.533, 0.547, -0.281]} scale={0} />
        <mesh name="AMDRyzen9-5950x002" geometry={nodes['AMDRyzen9-5950x002'].geometry} material={materials['AMDRyzen9-5950x']} position={[-0.557, 0.554, -0.176]} scale={0} />
        <group name="CorsairFanBlackv1_140mm" position={[-0.385, 0.526, 1.267]} scale={0}>
          <mesh name="Vert008" geometry={nodes.Vert008.geometry} material={materials.darkgrey} />
          <mesh name="Vert008_1" geometry={nodes.Vert008_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="CorsairFanWhite120mm" position={[-0.385, 0.526, 1.267]} scale={0}>
          <mesh name="Vert009" geometry={nodes.Vert009.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert009_1" geometry={nodes.Vert009_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanWhite140mm" position={[-0.385, 0.526, 1.267]} scale={0}>
          <mesh name="Vert014" geometry={nodes.Vert014.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert014_1" geometry={nodes.Vert014_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanBlack120mm" position={[-0.385, 0.526, 1.267]} scale={0}>
          <mesh name="Vert016" geometry={nodes.Vert016.geometry} material={materials.darkgrey} />
          <mesh name="Vert016_1" geometry={nodes.Vert016_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlack140mm" position={[-0.385, 0.526, 1.267]} scale={0}>
          <mesh name="Vert017" geometry={nodes.Vert017.geometry} material={materials.darkgrey} />
          <mesh name="Vert017_1" geometry={nodes.Vert017_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlackv1_120mm" position={[-0.385, 0.526, 1.267]} scale={0}>
          <mesh name="Vert019" geometry={nodes.Vert019.geometry} material={materials.darkgrey} />
          <mesh name="Vert019_1" geometry={nodes.Vert019_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="CorsairFanBlackv1_140mm001" position={[0.012, 0.526, 1.267]} scale={0}>
          <mesh name="Vert023" geometry={nodes.Vert023.geometry} material={materials.darkgrey} />
          <mesh name="Vert023_1" geometry={nodes.Vert023_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="CorsairFanWhite120mm001" position={[0.012, 0.526, 1.267]} scale={0}>
          <mesh name="Vert024" geometry={nodes.Vert024.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert024_1" geometry={nodes.Vert024_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanWhite140mm001" position={[0.012, 0.526, 1.267]} scale={0}>
          <mesh name="Vert025" geometry={nodes.Vert025.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert025_1" geometry={nodes.Vert025_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanBlack120mm001" position={[0.012, 0.526, 1.267]} scale={0}>
          <mesh name="Vert026" geometry={nodes.Vert026.geometry} material={materials.darkgrey} />
          <mesh name="Vert026_1" geometry={nodes.Vert026_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlack140mm001" position={[0.012, 0.526, 1.267]} scale={0}>
          <mesh name="Vert027" geometry={nodes.Vert027.geometry} material={materials.darkgrey} />
          <mesh name="Vert027_1" geometry={nodes.Vert027_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlackv1_120mm001" position={[0.012, 0.526, 1.267]} scale={0}>
          <mesh name="Vert028" geometry={nodes.Vert028.geometry} material={materials.darkgrey} />
          <mesh name="Vert028_1" geometry={nodes.Vert028_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="CorsairFanBlackv1_140mm002" position={[0.012, -0.208, 1.267]} scale={0}>
          <mesh name="Vert029" geometry={nodes.Vert029.geometry} material={materials.darkgrey} />
          <mesh name="Vert029_1" geometry={nodes.Vert029_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="CorsairFanWhite120mm002" position={[0.012, -0.208, 1.267]} scale={0}>
          <mesh name="Vert030" geometry={nodes.Vert030.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert030_1" geometry={nodes.Vert030_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanWhite140mm002" position={[0.012, -0.208, 1.267]} scale={0}>
          <mesh name="Vert031" geometry={nodes.Vert031.geometry} material={materials.WhiteMaterialImage} />
          <mesh name="Vert031_1" geometry={nodes.Vert031_1.geometry} material={materials.FanWhite} />
        </group>
        <group name="CorsairFanBlack120mm002" position={[0.012, -0.208, 1.267]} scale={0}>
          <mesh name="Vert032" geometry={nodes.Vert032.geometry} material={materials.darkgrey} />
          <mesh name="Vert032_1" geometry={nodes.Vert032_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlack140mm002" position={[0.012, -0.208, 1.267]} scale={0}>
          <mesh name="Vert033" geometry={nodes.Vert033.geometry} material={materials.darkgrey} />
          <mesh name="Vert033_1" geometry={nodes.Vert033_1.geometry} material={materials.BlackFan2nd} />
        </group>
        <group name="CorsairFanBlackv1_120mm002" position={[0.012, -0.208, 1.267]} scale={0}>
          <mesh name="Vert034" geometry={nodes.Vert034.geometry} material={materials.darkgrey} />
          <mesh name="Vert034_1" geometry={nodes.Vert034_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="HX850_Power_unit" position={[-0.275, -0.745, -1.515]} scale={0}>
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.PowerBox1200top} />
          <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials.PowerBoxHX1200back} />
          <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials.PowerBoxHX1200front} />
          <mesh name="Plane004_3" geometry={nodes.Plane004_3.geometry} material={materials.BlackMetalic} />
          <mesh name="Plane004_4" geometry={nodes.Plane004_4.geometry} material={materials.PowerBoxHX850side} />
          <mesh name="Plane004_5" geometry={nodes.Plane004_5.geometry} material={materials.PowerBoxHX850back} />
          <mesh name="Plane004_6" geometry={nodes.Plane004_6.geometry} material={materials.darkgrey} />
        </group>
        <group name="HX1200_Power_unit" position={[-0.159, -0.746, -1.289]} scale={0}>
          <mesh name="Plane065" geometry={nodes.Plane065.geometry} material={materials.PowerBox1200top} />
          <mesh name="Plane065_1" geometry={nodes.Plane065_1.geometry} material={materials.PowerBoxHX1200back} />
          <mesh name="Plane065_2" geometry={nodes.Plane065_2.geometry} material={materials.PowerBoxHX1200front} />
          <mesh name="Plane065_3" geometry={nodes.Plane065_3.geometry} material={materials.PowerBoxHX1200side} />
          <mesh name="Plane065_4" geometry={nodes.Plane065_4.geometry} material={materials.BlackMetalic} />
          <mesh name="Plane065_5" geometry={nodes.Plane065_5.geometry} material={materials.darkgrey} />
        </group>
        <group name="CX550_Power_unit" position={[-0.034, -0.681, -1.327]} scale={0}>
          <mesh name="Torus007" geometry={nodes.Torus007.geometry} material={materials.darkgrey} />
          <mesh name="Torus007_1" geometry={nodes.Torus007_1.geometry} material={materials.CX550Top} />
          <mesh name="Torus007_2" geometry={nodes.Torus007_2.geometry} material={materials.CX550Front} />
          <mesh name="Torus007_3" geometry={nodes.Torus007_3.geometry} material={materials.CX550Side} />
          <mesh name="Torus007_4" geometry={nodes.Torus007_4.geometry} material={materials.CX550Back} />
          <mesh name="Torus007_5" geometry={nodes.Torus007_5.geometry} material={materials.PowerBox1200top} />
          <mesh name="Torus007_6" geometry={nodes.Torus007_6.geometry} material={materials.PowerBoxHX1200back} />
          <mesh name="Torus007_7" geometry={nodes.Torus007_7.geometry} material={materials.PowerBoxHX1200front} />
          <mesh name="Torus007_8" geometry={nodes.Torus007_8.geometry} material={materials.PowerBoxHX1200front} />
        </group>
        <group name="MSIX370XPowerGamingTitatnum" position={[-0.225, 0.118, 1.521]} scale={0}>
          <mesh name="MSIX370XPowerGamingTitatnum_1" geometry={nodes.MSIX370XPowerGamingTitatnum_1.geometry} material={materials.darkgrey} />
          <mesh name="MSIX370XPowerGamingTitatnum_2" geometry={nodes.MSIX370XPowerGamingTitatnum_2.geometry} material={materials.MotherboardBaseFrontSide} />
          <mesh name="MSIX370XPowerGamingTitatnum_3" geometry={nodes.MSIX370XPowerGamingTitatnum_3.geometry} material={materials.MotherboardBaseBackSide} />
          <mesh name="MSIX370XPowerGamingTitatnum_4" geometry={nodes.MSIX370XPowerGamingTitatnum_4.geometry} material={materials.MetallicGrey} />
          <mesh name="MSIX370XPowerGamingTitatnum_5" geometry={nodes.MSIX370XPowerGamingTitatnum_5.geometry} material={materials.red} />
          <mesh name="MSIX370XPowerGamingTitatnum_6" geometry={nodes.MSIX370XPowerGamingTitatnum_6.geometry} material={materials.gold} />
          <mesh name="MSIX370XPowerGamingTitatnum_7" geometry={nodes.MSIX370XPowerGamingTitatnum_7.geometry} material={materials.lightdarkgrey} />
        </group>
        <group name="MSIX370XPowerGamingTitatnumSHIELD" position={[-0.109, -0.059, -0.34]} scale={0}>
          <mesh name="MSIX370XPowerGamingTitatnum001" geometry={nodes.MSIX370XPowerGamingTitatnum001.geometry} material={materials.darkgrey} />
          <mesh name="MSIX370XPowerGamingTitatnum001_1" geometry={nodes.MSIX370XPowerGamingTitatnum001_1.geometry} material={materials.MotherboardBaseFrontSide} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube199" geometry={nodes.Cube199.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube199_1" geometry={nodes.Cube199_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB001" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube034_1" geometry={nodes.Cube034_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB002" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube031_1" geometry={nodes.Cube031_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB003" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube032_1" geometry={nodes.Cube032_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB004" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube019_1" geometry={nodes.Cube019_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB005" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB006" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB007" position={[-0.431, 0.572, -0.144]} scale={0}>
          <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB008" position={[-0.64, 0.572, -0.144]} scale={0}>
          <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="Kingston_Fury_Beast_CL18_DDR4_8GB009" position={[-0.64, 0.572, -0.144]} scale={0}>
          <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['ktc beast frontside']} />
          <mesh name="Cube025_1" geometry={nodes.Cube025_1.geometry} material={materials['ktc beast backside']} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube303" geometry={nodes.Cube303.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube303_1" geometry={nodes.Cube303_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube303_2" geometry={nodes.Cube303_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz001" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube038_1" geometry={nodes.Cube038_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube038_2" geometry={nodes.Cube038_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz002" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube037_1" geometry={nodes.Cube037_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube037_2" geometry={nodes.Cube037_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz003" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube036_1" geometry={nodes.Cube036_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube036_2" geometry={nodes.Cube036_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz004" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz005" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube009_2" geometry={nodes.Cube009_2.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube009_3" geometry={nodes.Cube009_3.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz006" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube010_2" geometry={nodes.Cube010_2.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube010_3" geometry={nodes.Cube010_3.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz007" position={[-0.431, 0.534, -0.087]} scale={0}>
          <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube011_1" geometry={nodes.Cube011_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube011_2" geometry={nodes.Cube011_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz008" position={[-0.756, 0.534, -0.087]} scale={0}>
          <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube017_1" geometry={nodes.Cube017_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube017_2" geometry={nodes.Cube017_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="DIMM_16GB_DDR4_3600MHz009" position={[-0.756, 0.534, -0.087]} scale={0}>
          <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['HP 8GB RAM frontside']} />
          <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials['HP 8GB RAM backside']} />
          <mesh name="Cube018_2" geometry={nodes.Cube018_2.geometry} material={materials.MaterialRGB} />
        </group>
        <group name="NvidiaGeForceRTX3090" position={[-0.036, 0.022, 2.604]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090_1" geometry={nodes.NvidiaGeForceRTX3090_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090_2" geometry={nodes.NvidiaGeForceRTX3090_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090_3" geometry={nodes.NvidiaGeForceRTX3090_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090_4" geometry={nodes.NvidiaGeForceRTX3090_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090_5" geometry={nodes.NvidiaGeForceRTX3090_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090_6" geometry={nodes.NvidiaGeForceRTX3090_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090_7" geometry={nodes.NvidiaGeForceRTX3090_7.geometry} material={materials['Material.004']} />
        </group>
        <group name="NvidiaGeForceRTX3090001" position={[-0.036, -0.289, 2.604]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090001_1" geometry={nodes.NvidiaGeForceRTX3090001_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090001_2" geometry={nodes.NvidiaGeForceRTX3090001_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090001_3" geometry={nodes.NvidiaGeForceRTX3090001_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090001_4" geometry={nodes.NvidiaGeForceRTX3090001_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090001_5" geometry={nodes.NvidiaGeForceRTX3090001_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090001_6" geometry={nodes.NvidiaGeForceRTX3090001_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090001_7" geometry={nodes.NvidiaGeForceRTX3090001_7.geometry} material={materials['Material.004']} />
        </group>
        <group name="NvidiaGeForceRTX3090002" position={[-0.036, 0.022, 2.604]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090002_1" geometry={nodes.NvidiaGeForceRTX3090002_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090002_2" geometry={nodes.NvidiaGeForceRTX3090002_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090002_3" geometry={nodes.NvidiaGeForceRTX3090002_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090002_4" geometry={nodes.NvidiaGeForceRTX3090002_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090002_5" geometry={nodes.NvidiaGeForceRTX3090002_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090002_6" geometry={nodes.NvidiaGeForceRTX3090002_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090002_7" geometry={nodes.NvidiaGeForceRTX3090002_7.geometry} material={materials['Material.004']} />
        </group>
        <group name="NvidiaGeForceRTX3090003" position={[-0.036, 0.022, 2.604]} scale={0}>
          <mesh name="NvidiaGeForceRTX3090003_1" geometry={nodes.NvidiaGeForceRTX3090003_1.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3090003_2" geometry={nodes.NvidiaGeForceRTX3090003_2.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3090003_3" geometry={nodes.NvidiaGeForceRTX3090003_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3090003_4" geometry={nodes.NvidiaGeForceRTX3090003_4.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3090003_5" geometry={nodes.NvidiaGeForceRTX3090003_5.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3090003_6" geometry={nodes.NvidiaGeForceRTX3090003_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3090003_7" geometry={nodes.NvidiaGeForceRTX3090003_7.geometry} material={materials['Material.004']} />
        </group>
        <group name="NvidiaGeForceRTX3080" position={[-0.152, 0.028, 1.267]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080_1" geometry={nodes.NvidiaGeForceRTX3080_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080_2" geometry={nodes.NvidiaGeForceRTX3080_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080_3" geometry={nodes.NvidiaGeForceRTX3080_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080_4" geometry={nodes.NvidiaGeForceRTX3080_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080_5" geometry={nodes.NvidiaGeForceRTX3080_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080_6" geometry={nodes.NvidiaGeForceRTX3080_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080_7" geometry={nodes.NvidiaGeForceRTX3080_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080_8" geometry={nodes.NvidiaGeForceRTX3080_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3080001" position={[-0.152, -0.281, 1.267]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080001_1" geometry={nodes.NvidiaGeForceRTX3080001_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080001_2" geometry={nodes.NvidiaGeForceRTX3080001_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080001_3" geometry={nodes.NvidiaGeForceRTX3080001_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080001_4" geometry={nodes.NvidiaGeForceRTX3080001_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080001_5" geometry={nodes.NvidiaGeForceRTX3080001_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080001_6" geometry={nodes.NvidiaGeForceRTX3080001_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080001_7" geometry={nodes.NvidiaGeForceRTX3080001_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080001_8" geometry={nodes.NvidiaGeForceRTX3080001_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3080002" position={[-0.152, 0.132, 1.267]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080002_1" geometry={nodes.NvidiaGeForceRTX3080002_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080002_2" geometry={nodes.NvidiaGeForceRTX3080002_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080002_3" geometry={nodes.NvidiaGeForceRTX3080002_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080002_4" geometry={nodes.NvidiaGeForceRTX3080002_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080002_5" geometry={nodes.NvidiaGeForceRTX3080002_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080002_6" geometry={nodes.NvidiaGeForceRTX3080002_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080002_7" geometry={nodes.NvidiaGeForceRTX3080002_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080002_8" geometry={nodes.NvidiaGeForceRTX3080002_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3080003" position={[-0.152, 0.132, 1.267]} scale={0}>
          <mesh name="NvidiaGeForceRTX3080003_1" geometry={nodes.NvidiaGeForceRTX3080003_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3080003_2" geometry={nodes.NvidiaGeForceRTX3080003_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3080003_3" geometry={nodes.NvidiaGeForceRTX3080003_3.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3080003_4" geometry={nodes.NvidiaGeForceRTX3080003_4.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3080003_5" geometry={nodes.NvidiaGeForceRTX3080003_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3080003_6" geometry={nodes.NvidiaGeForceRTX3080003_6.geometry} material={materials.RTX3080front} />
          <mesh name="NvidiaGeForceRTX3080003_7" geometry={nodes.NvidiaGeForceRTX3080003_7.geometry} material={materials.GraphicsCardSocket} />
          <mesh name="NvidiaGeForceRTX3080003_8" geometry={nodes.NvidiaGeForceRTX3080003_8.geometry} material={materials.MetallicGrey} />
        </group>
        <group name="NvidiaGeForceRTX3070" position={[-0.369, 0.023, 1.439]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070_1" geometry={nodes.NvidiaGeForceRTX3070_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070_2" geometry={nodes.NvidiaGeForceRTX3070_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070_3" geometry={nodes.NvidiaGeForceRTX3070_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070_4" geometry={nodes.NvidiaGeForceRTX3070_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070_5" geometry={nodes.NvidiaGeForceRTX3070_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070_6" geometry={nodes.NvidiaGeForceRTX3070_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070_7" geometry={nodes.NvidiaGeForceRTX3070_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070_8" geometry={nodes.NvidiaGeForceRTX3070_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <group name="NvidiaGeForceRTX3070001" position={[-0.369, -0.29, 1.439]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070001_1" geometry={nodes.NvidiaGeForceRTX3070001_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070001_2" geometry={nodes.NvidiaGeForceRTX3070001_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070001_3" geometry={nodes.NvidiaGeForceRTX3070001_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070001_4" geometry={nodes.NvidiaGeForceRTX3070001_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070001_5" geometry={nodes.NvidiaGeForceRTX3070001_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070001_6" geometry={nodes.NvidiaGeForceRTX3070001_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070001_7" geometry={nodes.NvidiaGeForceRTX3070001_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070001_8" geometry={nodes.NvidiaGeForceRTX3070001_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <group name="NvidiaGeForceRTX3070002" position={[-0.369, 0.023, 1.439]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070002_1" geometry={nodes.NvidiaGeForceRTX3070002_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070002_2" geometry={nodes.NvidiaGeForceRTX3070002_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070002_3" geometry={nodes.NvidiaGeForceRTX3070002_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070002_4" geometry={nodes.NvidiaGeForceRTX3070002_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070002_5" geometry={nodes.NvidiaGeForceRTX3070002_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070002_6" geometry={nodes.NvidiaGeForceRTX3070002_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070002_7" geometry={nodes.NvidiaGeForceRTX3070002_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070002_8" geometry={nodes.NvidiaGeForceRTX3070002_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <group name="NvidiaGeForceRTX3070003" position={[-0.369, 0.023, 1.439]} scale={0}>
          <mesh name="NvidiaGeForceRTX3070003_1" geometry={nodes.NvidiaGeForceRTX3070003_1.geometry} material={materials.darkgrey} />
          <mesh name="NvidiaGeForceRTX3070003_2" geometry={nodes.NvidiaGeForceRTX3070003_2.geometry} material={materials['RTX3090 front']} />
          <mesh name="NvidiaGeForceRTX3070003_3" geometry={nodes.NvidiaGeForceRTX3070003_3.geometry} material={materials.RTX3090top} />
          <mesh name="NvidiaGeForceRTX3070003_4" geometry={nodes.NvidiaGeForceRTX3070003_4.geometry} material={materials.RTX3090back} />
          <mesh name="NvidiaGeForceRTX3070003_5" geometry={nodes.NvidiaGeForceRTX3070003_5.geometry} material={materials.RTX3090bottom} />
          <mesh name="NvidiaGeForceRTX3070003_6" geometry={nodes.NvidiaGeForceRTX3070003_6.geometry} material={materials.MetallicGrey} />
          <mesh name="NvidiaGeForceRTX3070003_7" geometry={nodes.NvidiaGeForceRTX3070003_7.geometry} material={materials['RTX3070 front']} />
          <mesh name="NvidiaGeForceRTX3070003_8" geometry={nodes.NvidiaGeForceRTX3070003_8.geometry} material={materials.GraphicsCardSocket2} />
        </group>
        <group name="AsusRogStrixB350-I" position={[-0.26, 0.481, 1.829]} scale={0}>
          <mesh name="AsusRogStrixB350-I_1" geometry={nodes['AsusRogStrixB350-I_1'].geometry} material={materials.darkgrey} />
          <mesh name="AsusRogStrixB350-I_2" geometry={nodes['AsusRogStrixB350-I_2'].geometry} material={materials['AsusRogStrixB350-IBase']} />
          <mesh name="AsusRogStrixB350-I_3" geometry={nodes['AsusRogStrixB350-I_3'].geometry} material={materials['AsusRogStixB350-IBaseBack']} />
          <mesh name="AsusRogStrixB350-I_4" geometry={nodes['AsusRogStrixB350-I_4'].geometry} material={materials.MetallicGrey} />
          <mesh name="AsusRogStrixB350-I_5" geometry={nodes['AsusRogStrixB350-I_5'].geometry} material={materials.gold} />
          <mesh name="AsusRogStrixB350-I_6" geometry={nodes['AsusRogStrixB350-I_6'].geometry} material={materials.lightdarkgrey} />
          <mesh name="AsusRogStrixB350-I_7" geometry={nodes['AsusRogStrixB350-I_7'].geometry} material={materials.MotherboardBaseFrontSide} />
          <mesh name="AsusRogStrixB350-I_8" geometry={nodes['AsusRogStrixB350-I_8'].geometry} material={materials.red} />
          <mesh name="AsusRogStrixB350-I_9" geometry={nodes['AsusRogStrixB350-I_9'].geometry} material={materials.DarkBlue} />
          <mesh name="AsusRogStrixB350-I_10" geometry={nodes['AsusRogStrixB350-I_10'].geometry} material={materials.WhiteMaterialImage} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pc_parts/pc_cases/PhanteksEclipseP300Midtower.glb')

export default PhanteksEclipseP300Midtower