/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Samsung970EVOPlus.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const Samsung970EVOPlus=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/storage/Samsung970EVOPlus.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.115, -0.02, 0]}>
        <mesh geometry={nodes.Plane012.geometry} material={materials.Samsung970EVOPlusfront} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.Samsung970EVOPlusback} />
        <mesh geometry={nodes.Plane012_2.geometry} material={materials.darkgrey} />
      </group>
    </group>
  )
}

const Samsung970EVOPlusCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 3}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <Samsung970EVOPlus/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/storage/Samsung970EVOPlus.glb')

export default Samsung970EVOPlusCanvas