/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Samsung870EVO.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const Samsung870EVO=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/storage/Samsung870EVO.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.019, 0, 0]}>
        <mesh geometry={nodes.Samsung870EVO_1.geometry} material={materials.Samsung870EVO_back} />
        <mesh geometry={nodes.Samsung870EVO_2.geometry} material={materials.Samsung870EVO_front} />
      </group>
    </group>
  )
}

const Samsung870EVOCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 5}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <Samsung870EVO/>
        </Suspense>
      </Canvas>
  )
}

useGLTF.preload('/pc_parts/storage/Samsung870EVO.glb')

export default Samsung870EVOCanvas