/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 SeagateBarraCuda2TB.glb 
*/

import React, { Suspense, useRef } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

const SeagateBarraCuda2TB=(props)=> {
  const { nodes, materials } = useGLTF('/pc_parts/storage/SeagateBarraCuda2TB.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.07, 0]} rotation={[0, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Cube598.geometry} material={materials.Samsung870EVO_back} />
        <mesh geometry={nodes.Cube598_1.geometry} material={materials.darkgrey} />
        <mesh geometry={nodes.Cube598_2.geometry} material={materials.MetallicGrey} />
        <mesh geometry={nodes.Cube598_3.geometry} material={materials.SeagateBarraCuda2TBfront} />
        <mesh geometry={nodes.Cube598_4.geometry} material={materials.SeagateBarraCuda2TBback} />
      </group>
    </group>
  )
}

const SeagateBarraCuda2TBCanvas=()=>{
  return(
    <Canvas
      camera={{fov: 10}}>
        <Suspense>
          <ambientLight intensity={2} color={"white"}/>
          <OrbitControls/>
          <SeagateBarraCuda2TB/>
        </Suspense>
    </Canvas>
  )
}

useGLTF.preload('/pc_parts/storage/SeagateBarraCuda2TB.glb')

export default SeagateBarraCuda2TBCanvas